/** Auto-generated by npm run pages:generate — do not edit manually. */
import type { SearchQuerySeed } from "@/lib/search-query-seeds";

export const GENERATED_SEARCH_QUERY_SEEDS: SearchQuerySeed[] = [
  { slug: "my-first-million-business", phrase: "my first million business", title: "My First Million Business — video moments", description: "20 indexed moments across 15 videos for \"my first million business\"." },
  { slug: "my-first-million-side-hustle", phrase: "my first million side-hustle", title: "My First Million Side-hustle — video moments", description: "20 indexed moments across 14 videos for \"my first million side-hustle\"." },
  { slug: "the-net-ninja-javascript", phrase: "the net ninja javascript", title: "The Net Ninja Javascript — video moments", description: "20 indexed moments across 19 videos for \"the net ninja javascript\"." },
  { slug: "the-net-ninja-react", phrase: "the net ninja react", title: "The Net Ninja React — video moments", description: "20 indexed moments across 19 videos for \"the net ninja react\"." },
  { slug: "the-net-ninja-web-development", phrase: "the net ninja web-development", title: "The Net Ninja Web-development — video moments", description: "20 indexed moments across 19 videos for \"the net ninja web-development\"." },
  { slug: "the-plain-bagel-index-funds", phrase: "the plain bagel index-funds", title: "The Plain Bagel Index-funds — video moments", description: "20 indexed moments across 19 videos for \"the plain bagel index-funds\"." },
  { slug: "google-cloud", phrase: "google cloud", title: "Google Cloud — video moments", description: "17 indexed moments across 13 videos for \"google cloud\"." },
  { slug: "javascript-code", phrase: "javascript code", title: "Javascript Code — video moments", description: "15 indexed moments across 9 videos for \"javascript code\"." },
  { slug: "web-server", phrase: "web server", title: "Web Server — video moments", description: "20 indexed moments across 12 videos for \"web server\"." },
  { slug: "web-page", phrase: "web page", title: "Web Page — video moments", description: "20 indexed moments across 11 videos for \"web page\"." },
  { slug: "create-react", phrase: "create react", title: "Create React — video moments", description: "16 indexed moments across 8 videos for \"create react\"." },
  { slug: "react-app", phrase: "react app", title: "React App — video moments", description: "14 indexed moments across 8 videos for \"react app\"." },
  { slug: "i'll-talk", phrase: "i'll talk", title: "I'll Talk — video moments", description: "20 indexed moments across 12 videos for \"i'll talk\"." },
  { slug: "every-time", phrase: "every time", title: "Every Time — video moments", description: "20 indexed moments across 11 videos for \"every time\"." },
  { slug: "react-component", phrase: "react component", title: "React Component — video moments", description: "16 indexed moments across 11 videos for \"react component\"." },
  { slug: "react-router", phrase: "react router", title: "React Router — video moments", description: "11 indexed moments across 6 videos for \"react router\"." },
  { slug: "create-exercise", phrase: "create exercise", title: "Create Exercise — video moments", description: "6 indexed moments across 4 videos for \"create exercise\"." },
  { slug: "exercise-list", phrase: "exercise list", title: "Exercise List — video moments", description: "4 indexed moments across 2 videos for \"exercise list\"." },
  { slug: "find-out", phrase: "find out", title: "Find Out — video moments", description: "20 indexed moments across 12 videos for \"find out\"." },
  { slug: "programming-language", phrase: "programming language", title: "Programming Language — video moments", description: "20 indexed moments across 10 videos for \"programming language\"." },
  { slug: "index-html", phrase: "index html", title: "Index Html — video moments", description: "15 indexed moments across 9 videos for \"index html\"." },
];
