export type SeedChannelVideo = {
  videoId: string;
  topic: string;
  priority: number;
};

export type SeedChannel = {
  slug: string;
  name: string;
  category: string;
  videos: SeedChannelVideo[];
};

export const SEED_CHANNEL_CATALOG: SeedChannel[] = [
  {
    slug: "freecodecamp",
    name: "freeCodeCamp",
    category: "programming tutorials",
    videos: [
      { videoId: "eIrMbAQqh4Q", topic: "java", priority: 1 },
      { videoId: "bMknfKXYPfb", topic: "react", priority: 1 },
      { videoId: "Oe421EPjBEg", topic: "nodejs", priority: 1 },
      { videoId: "RBSGKlAvoiM", topic: "data-structures", priority: 1 },
      { videoId: "HXV3zeQKq0E", topic: "sql", priority: 1 },
      { videoId: "N4VDN1jhg2U", topic: "git", priority: 1 },
      { videoId: "kqtD5kpI9F0", topic: "cpp", priority: 1 },
      { videoId: "mU6anWqZJcc", topic: "responsive-design", priority: 1 },
      { videoId: "8ext9G7xspg", topic: "golang", priority: 2 },
      { videoId: "8jLOx1hD3_o", topic: "csharp", priority: 1 },
      { videoId: "w7ejDZ8SWv8", topic: "react-native", priority: 2 },
      { videoId: "TBoSDECjPSY", topic: "expressjs", priority: 2 },
      { videoId: "1Rs2ND1ryYc", topic: "css", priority: 1 },
      { videoId: "fqMOXHJfhYk", topic: "docker", priority: 1 },
      { videoId: "t8pPdKYpowI", topic: "kotlin", priority: 2 },
      { videoId: "nu_pCVPKzTk", topic: "fullstack-javascript", priority: 1 },
      { videoId: "3PHXvlpOkfE", topic: "nextjs", priority: 1 },
      { videoId: "41-qW0nQ5gQ", topic: "svelte", priority: 2 },
      { videoId: "gXLjWRteuWI", topic: "rust", priority: 1 },
      { videoId: "8JJ101D3knE", topic: "git-github", priority: 2 },
      { videoId: "yaqe1qesAJ8", topic: "dynamic-programming", priority: 2 },
      { videoId: "2ISbhNrSalI", topic: "cs50-week1", priority: 1 },
      { videoId: "KJgsSFOSQv0", topic: "c-programming", priority: 1 },
      { videoId: "zY02NjoXK7k", topic: "php", priority: 2 },
      { videoId: "9cKsq14Kfsw", topic: "mongodb", priority: 1 },
      { videoId: "i_LwzRVP7bg", topic: "bootstrap", priority: 2 },
      { videoId: "2ybLD6_2gKM", topic: "seo", priority: 3 },
      { videoId: "qIsgdOVGA04", topic: "excel", priority: 2 },
      { videoId: "gB1F9G0JXOo", topic: "unreal-engine", priority: 2 },
      { videoId: "B31LgI4Y4DQ", topic: "terraform", priority: 1 },
      { videoId: "3c-iBn73dDE", topic: "aws", priority: 1 },
      { videoId: "HkvKkDpt0hs", topic: "django", priority: 1 },
      { videoId: "xWi8n2DQX2k", topic: "laravel", priority: 1 },
      { videoId: "GoCF3RLr7b8", topic: "spring-boot", priority: 1 },
      { videoId: "PZ7lDRQJroe", topic: "flask", priority: 1 },
      { videoId: "pQRNCAgH5Jg", topic: "bootstrap", priority: 2 },
      { videoId: "9kkem8v-8Z0", topic: "linux", priority: 1 },
      { videoId: "3YS713M0aek", topic: "cybersecurity", priority: 1 },
      { videoId: "BI1Ak2DJ9yk", topic: "ethical-hacking", priority: 2 },
      { videoId: "AwesGL0cnF0", topic: "ui-ux", priority: 2 },
      { videoId: "9zKGFVTMF-M", topic: "blender", priority: 3 },
      { videoId: "7SnyY0KTUcg", topic: "data-analysis", priority: 1 },
      { videoId: "LfaMVlDaE5c", topic: "power-bi", priority: 2 },
      { videoId: "CLLTZTU8tuo", topic: "tableau", priority: 2 },
      { videoId: "FgzE3v6sv0U", topic: "bootstrap", priority: 2 },
      { videoId: "pTFZFgx4IbM", topic: "flutter", priority: 1 },
      { videoId: "VPvVD8t02Z8", topic: "flutter", priority: 2 },
      { videoId: "wN0Vc7-redY", topic: "csharp", priority: 1 },
      { videoId: "qB2U2eWx3uA", topic: "unity", priority: 2 },
      { videoId: "G_EptEUsIkw", topic: "angular", priority: 1 },
      { videoId: "2qQWl9H3Y1s", topic: "swift", priority: 1 },
      { videoId: "pE0a4KnSE22", topic: "kotlin-android", priority: 2 },
      { videoId: "1Xj73ygVVoo", topic: "react-native", priority: 2 },
      { videoId: "SLB4Z5VoWNE", topic: "kubernetes", priority: 1 },
      { videoId: "jZdaM2OLfmQ", topic: "git-github", priority: 2 },
      { videoId: "zJch2fphYYA", topic: "devops", priority: 2 },
      { videoId: "nu6mMF4BgOI", topic: "postgresql", priority: 1 },
      { videoId: "QIyk-gU9b18", topic: "redis", priority: 2 },
      { videoId: "1PnVq36WuJE", topic: "ruby", priority: 2 },
      { videoId: "vp9sH8kPL88", topic: "elixir", priority: 3 },
      { videoId: "9z12uzaicRw", topic: "scala", priority: 3 },
      { videoId: "1W3yy0YJpjE", topic: "haskell", priority: 3 },
      { videoId: "1OALW-RrRVk", topic: "assembly", priority: 3 },
      { videoId: "M8HrtodtpL4", topic: "blockchain", priority: 2 },
      { videoId: "PkZNo7MFNFg", topic: "javascript", priority: 1 },
      { videoId: "rfscVS0vtbw", topic: "python", priority: 1 },
      { videoId: "jS4aFq5-91M", topic: "javascript-full-course", priority: 1 },
      { videoId: "8DvywoWv6fI", topic: "python-for-everybody", priority: 1 },
      { videoId: "jH85McHenvw", topic: "python-types", priority: 1 },
      { videoId: "RGOj5yH7evk", topic: "git-github", priority: 1 },
      { videoId: "kqtD5dpn9C8", topic: "python-scrimba", priority: 1 },
      { videoId: "Oe421EPjeBE", topic: "flutter-full-course", priority: 1 },
      { videoId: "qz0aGYrrlhU", topic: "html-css-javascript", priority: 1 },
      { videoId: "wN0x9eZLix4", topic: "data-structures-algorithms-python", priority: 1 },
      { videoId: "eIrMbAQSU34", topic: "java-full-course", priority: 1 },
      { videoId: "c4OyfL5o7DU", topic: "nodejs-full-course", priority: 1 },
      { videoId: "09_LlHjoEiY", topic: "react-native", priority: 1 },
      { videoId: "TlB_eWDSMt4", topic: "nodejs-tutorial", priority: 1 },
      { videoId: "zJSY8tbf_ys", topic: "flask-python", priority: 1 },
      { videoId: "HXV3zeQKqGY", topic: "sql-fundamentals", priority: 1 },
      { videoId: "fis26HvvDII", topic: "angular-full-course", priority: 1 },
      { videoId: "4UZrsTqkcW4", topic: "backend-development", priority: 1 },
      { videoId: "ua-CiDNNj30", topic: "backend-python", priority: 1 },
      { videoId: "1PnVor36_40", topic: "devops-ci-cd", priority: 1 },
      { videoId: "1WmNXEVia8I", topic: "algorithms-python", priority: 1 },
      { videoId: "8hly31xKli0", topic: "express-mongodb", priority: 1 },
      { videoId: "8aGhZQkoFbQ", topic: "javascript-event-loop", priority: 1 },
      { videoId: "x0uinJvhNxI", topic: "bootstrap-4", priority: 2 },
      { videoId: "M7lc1UVf-VE", topic: "html5-css3", priority: 1 },
      { videoId: "Wf2eSG3owoA", topic: "docker-kubernetes", priority: 1 },
      { videoId: "kTp5xUtcalw", topic: "docker-kubernetes-hands-on", priority: 1 },
      { videoId: "d6WC5n9G_sM", topic: "kubernetes-beginners", priority: 1 },
      { videoId: "_4uQI4ihGVU", topic: "kubernetes-deep-dive", priority: 1 },
      { videoId: "fqMOX6JJhGo", topic: "docker-devops", priority: 1 },
      { videoId: "7HKot-brXFE", topic: "aws-cloud-practitioner", priority: 1 },
      { videoId: "4m9j6hlbf4g", topic: "it-fundamentals", priority: 1 },
      { videoId: "C842vFY5kRo", topic: "system-design", priority: 1 },
      { videoId: "CcrC5zSv1iA", topic: "llm-fine-tuning", priority: 1 },
      { videoId: "BiA08jfr4RU", topic: "web-dev-projects", priority: 1 },
      { videoId: "SqQUQHdYWyc", topic: "cuda-programming", priority: 2 },
      { videoId: "uHNOqKdqQas", topic: "jenkins-devops", priority: 2 },
      { videoId: "tVskbekONlw", topic: "mlops-mlflow", priority: 1 },
      { videoId: "R8h_gpSpEVU", topic: "deploying-ai-models", priority: 1 },
      { videoId: "gh2_PhgZGsM", topic: "claude-code", priority: 1 },
      { videoId: "XKOR4h3CrwE", topic: "gemini-cli", priority: 2 },
      { videoId: "WG5PJ8nFjv0", topic: "neural-networks", priority: 1 },
      { videoId: "gfDE2a9MXdw", topic: "tensorflow", priority: 1 },
      { videoId: "tPYj3fFJGjk", topic: "transformers", priority: 1 },
      { videoId: "7eh4dLRsPhM", topic: "data-science", priority: 1 },
      { videoId: "tx7uPw278zw", topic: "bootstrap-5", priority: 1 },
      { videoId: "NWONeJKn6kc", topic: "machine-learning-python", priority: 1 },
      { videoId: "VmQ4qUJKdNA", topic: "algorithms", priority: 1 },
      { videoId: "i6OiDI95OCQ", topic: "docker", priority: 1 },
      { videoId: "D72ZrfSyIFs", topic: "javascript-projects", priority: 1 },
      { videoId: "qxMowoLG1nU", topic: "machine-learning", priority: 1 },
      { videoId: "tqv0I8qd0HI", topic: "pytorch", priority: 1 },
      { videoId: "0FTFbBgXWKU", topic: "apache-spark", priority: 2 },
      { videoId: "9kHcLRAhXZY", topic: "kafka", priority: 2 },
      { videoId: "5eSolROwW8E", topic: "r-programming", priority: 2 },
      { videoId: "30lx5KP8GLg", topic: "typescript", priority: 1 },
      { videoId: "BwuLxPH8IDs", topic: "typescript-course", priority: 1 },
      { videoId: "0ik6l4pCcJA", topic: "tailwind-css", priority: 1 },
      { videoId: "xW7hn3LCvic", topic: "javascript-algorithms", priority: 1 },
      { videoId: "-leIp449qXA", topic: "automation-zapier", priority: 2 },
      { videoId: "zBJB8zLpBNA", topic: "linux-command-line", priority: 1 },
      { videoId: "Amq-urqMOD4", topic: "vue-full-course", priority: 1 },
      { videoId: "iW9wy_Jct6E", topic: "sveltekit", priority: 1 },
      { videoId: "GPv9cjHvK0M", topic: "linux-administration", priority: 1 },
      { videoId: "Cy9BoVm6Zd4", topic: "solidity-smart-contracts", priority: 1 },
      { videoId: "RGKpSfhZkPM", topic: "web3-blockchain", priority: 2 },
      { videoId: "G3h2r404IV8", topic: "ethical-hacking-2024", priority: 1 },
      { videoId: "3JJIQ32GHXs", topic: "digital-forensics", priority: 2 },
      { videoId: "Po8zNc7ju_0", topic: "astro-framework", priority: 1 },
      { videoId: "R9SmhmQ6Ue0", topic: "html-css-design", priority: 1 },
      { videoId: "AAoeSIQIR2w", topic: "bootstrap-portfolio", priority: 2 },
      { videoId: "ScKCyC7ISrk", topic: "sass-scss", priority: 2 },
      { videoId: "8DvyzeWtfqM", topic: "dart-programming", priority: 2 },
      { videoId: "VFuotXOk8_Q", topic: "julia-programming", priority: 3 },
      { videoId: "7CqJlxBYj-M", topic: "perl-programming", priority: 3 },
      { videoId: "qCRNB1z1ErM", topic: "lua-programming", priority: 3 },
      { videoId: "uQcTS7A-qGA", topic: "deno-runtime", priority: 2 }
    ],
  },
  {
    slug: "mit-opencourseware",
    name: "MIT OpenCourseWare",
    category: "programming tutorials",
    videos: [
      { videoId: "VyWAvY2CF9c", topic: "algorithms", priority: 1 },
      { videoId: "2ePf9rue1Ao", topic: "algorithms", priority: 1 },
      { videoId: "WUvTyaaNkzM", topic: "mathematics", priority: 2 },
      { videoId: "70bSF1MN8fk", topic: "computer-science", priority: 1 },
      { videoId: "W5J5JHal5-c", topic: "algorithms", priority: 2 },
      { videoId: "nBuS-WjidY8", topic: "linear-algebra", priority: 1 },
      { videoId: "ZA-tUyM_y7s", topic: "6-006-algorithms", priority: 1 },
      { videoId: "CHhwJjR0mZA", topic: "6-006-dynamic-arrays", priority: 1 },
      { videoId: "OQ5jsbhAv_M", topic: "6-006-divide-conquer", priority: 1 },
      { videoId: "HtSuA80QTyo", topic: "6-006-peak-finding", priority: 1 },
      { videoId: "C1lhuz6pZC0", topic: "6-006-sorting", priority: 1 },
      { videoId: "IPSaG9RRc-k", topic: "6-006-problem-session", priority: 1 },
      { videoId: "J7vHQiTn88Q", topic: "18-06-linear-algebra", priority: 1 },
      { videoId: "QkxuFQkm8Eo", topic: "18-06-elimination", priority: 1 },
      { videoId: "lhyC6h08jVI", topic: "18-06-multiplication", priority: 1 },
      { videoId: "rGldnwTlwfU", topic: "18-06-factorization", priority: 1 },
      { videoId: "c2xH2zU99b4", topic: "18-06-transposes", priority: 1 }
    ],
  },
  {
    slug: "harvard-cs50",
    name: "Harvard CS50",
    category: "programming tutorials",
    videos: [
      { videoId: "8mAITcNt710", topic: "artificial-intelligence", priority: 1 },
      { videoId: "5q87K1WaoDR", topic: "python", priority: 1 },
      { videoId: "cwtpLIWylAw", topic: "lecture-1-c-2024", priority: 1 },
      { videoId: "jZzyERW7h1A", topic: "lecture-3-algorithms", priority: 1 },
      { videoId: "0euvEdPwQnQ", topic: "lecture-5-data-structures", priority: 1 },
      { videoId: "EHi0RDZ31VA", topic: "lecture-6-python", priority: 1 },
      { videoId: "89cbCbWrM4U", topic: "lecture-1-c-2025", priority: 1 },
      { videoId: "zYOMDD4v8-U", topic: "lecture-2-c-2024", priority: 1 },
      { videoId: "1WfOAfxZSL8", topic: "lecture-4-memory", priority: 1 },
      { videoId: "iBB4Gwa2vNU", topic: "lecture-7-python", priority: 1 },
      { videoId: "9TycLR0QuqI", topic: "lecture-8-python", priority: 1 },
      { videoId: "9bZkp7q19f0", topic: "lecture-9-flask", priority: 1 }
    ],
  },
  {
    slug: "programming-with-mosh",
    name: "Programming with Mosh",
    category: "programming tutorials",
    videos: [
      { videoId: "W6NZfCO5XIk", topic: "javascript-basics", priority: 1 },
      { videoId: "SqcY0GlETPk", topic: "typescript", priority: 1 },
      { videoId: "_uQrJ0TkZlc", topic: "python-basics", priority: 1 },
      { videoId: "Rf-sc-brCQ4", topic: "react-native", priority: 2 }
    ],
  },
  {
    slug: "traversy-media",
    name: "Traversy Media",
    category: "programming tutorials",
    videos: [
      { videoId: "C5Q76MPdcgQ", topic: "nodejs-crash-course", priority: 2 },
      { videoId: "hdI2bqOjy3c", topic: "javascript", priority: 2 },
      { videoId: "PoRJizFvM7s", topic: "react", priority: 1 },
      { videoId: "3q1t5YcUAb8", topic: "mern-stack", priority: 1 },
      { videoId: "bkV9g5LtSgk", topic: "python", priority: 2 },
      { videoId: "yDJCDHA5ni0", topic: "react-hooks", priority: 1 },
      { videoId: "OFS90tXvk9Q", topic: "javascript", priority: 1 },
      { videoId: "4UZrsTqkcTI", topic: "nextjs", priority: 1 },
      { videoId: "SBmSRk3Feww", topic: "vue", priority: 1 },
      { videoId: "Ke90YMEj5kY", topic: "mongodb", priority: 2 },
      { videoId: "32M1al-Y6Ag", topic: "nodejs-crash-course-2024", priority: 1 },
      { videoId: "LDB4uaJ87e0", topic: "react-crash-course-2024", priority: 1 },
      { videoId: "SBvmnHTQIPY", topic: "nodejs-mongodb-oauth", priority: 1 },
      { videoId: "-0exw-9YJBo", topic: "mern-express-api", priority: 1 },
      { videoId: "fBNz5xF-Kx4", topic: "nodejs-crash-course", priority: 1 },
      { videoId: "Oive66jrwBs", topic: "mern-social-network", priority: 1 },
      { videoId: "3aGSqasVPsI", topic: "tailwind-crash", priority: 1 },
      { videoId: "UB1O30fR-EE", topic: "html-css-crash", priority: 1 },
      { videoId: "1uFY60CESlM", topic: "vanilla-javascript", priority: 1 },
      { videoId: "5fb2aPlgoys", topic: "django-crash", priority: 1 },
      { videoId: "8TMQcRcBnW8", topic: "fastapi-crash", priority: 1 },
      { videoId: "XCifkDC0yXA", topic: "react-native-crash", priority: 1 },
      { videoId: "G1Nr6N0Figk", topic: "flask-python", priority: 1 },
      { videoId: "7lCZCPAK5Yc", topic: "django-blog", priority: 1 },
      { videoId: "NgaypNQ0DWg", topic: "php-mvc", priority: 2 },
      { videoId: "qlED1bFJ7f4", topic: "laravel", priority: 1 },
      { videoId: "TwGRAbFBoqk", topic: "angular-crash", priority: 1 },
      { videoId: "BN_w0ujrnKy", topic: "graphql", priority: 1 },
      { videoId: "m_u6P5k0vP0", topic: "nextjs-14", priority: 1 },
      { videoId: "tN6oJu2DqCM", topic: "react-context", priority: 2 },
      { videoId: "DwGYhESO13M", topic: "http-crash", priority: 2 }
    ],
  },
  {
    slug: "lex-fridman",
    name: "Lex Fridman",
    category: "AI podcasts",
    videos: [
      { videoId: "uX9W5DglMow", topic: "elon-musk", priority: 1 },
      { videoId: "gk4tEO4jDUM", topic: "sadhguru", priority: 2 },
      { videoId: "jfqwHT3QgWQ", topic: "jordan-peterson", priority: 2 },
      { videoId: "nzfMk4LBRmQ", topic: "turing-award", priority: 1 },
      { videoId: "vjMqTEbi9Vo", topic: "nvidia", priority: 1 },
      { videoId: "tYrdA4GiiBw", topic: "mark-zuckerberg", priority: 1 },
      { videoId: "-wx-vm4z5gs", topic: "robert-greene", priority: 2 },
      { videoId: "Whtt2H5_isM", topic: "max-tegmark", priority: 1 },
      { videoId: "mwKJfNYwvm8", topic: "eric-weinstein", priority: 2 },
      { videoId: "Q0nGo2-y0xY", topic: "donald-knuth", priority: 1 },
      { videoId: "JN3KPFbWCy8", topic: "elon-musk", priority: 2 },
      { videoId: "jvqFAi7vkBc", topic: "elon-musk", priority: 2 },
      { videoId: "rIpUf-Vy2JA", topic: "richard-feynman", priority: 2 },
      { videoId: "Z3_PwvvfxIU", topic: "programming", priority: 2 },
      { videoId: "SGSOCuByo24", topic: "space-exploration", priority: 2 },
      { videoId: "P6prRXkI5HM", topic: "literature", priority: 3 },
      { videoId: "XkY2DOUCWMU", topic: "jeff-bezos", priority: 2 },
      { videoId: "sY8-YISYpVu", topic: "demis-hassabis", priority: 1 },
      { videoId: "mC43CHIhjTQ", topic: "andrew-ng", priority: 1 },
      { videoId: "U0wbhLNSk-s", topic: "yann-lecun", priority: 1 },
      { videoId: "cFUUS5ZKY2s", topic: "joscha-bach", priority: 2 },
      { videoId: "hg44HjfEB6E", topic: "ray-kurzweil", priority: 1 },
      { videoId: "t06RUxP5_cU", topic: "roger-penrose", priority: 2 },
      { videoId: "59bMfm-Orns", topic: "vitalik-buterin", priority: 1 },
      { videoId: "KQ-9oAznq0w", topic: "john-carmack", priority: 1 },
      { videoId: "W87vgxZ-uXs", topic: "francois-chollet", priority: 1 },
      { videoId: "iZjby1IDH8k", topic: "yuval-harari", priority: 2 },
      { videoId: "NHnfuj7iDJc", topic: "george-hotz", priority: 2 },
      { videoId: "gPfpei_VShQ", topic: "ben-goertzel", priority: 2 },
      { videoId: "vfYmkj4rC3Q", topic: "michio-kaku", priority: 2 },
      { videoId: "iFjMf6zzD0Q", topic: "sam-harris", priority: 2 },
      { videoId: "MV5vvr8cfNw", topic: "pieter-abbeel", priority: 1 },
      { videoId: "Gfr50K6cVaY", topic: "andrew-bustamante", priority: 2 },
      { videoId: "ZPUtA3tN6PE", topic: "david-fravor", priority: 2 },
      { videoId: "tYKRiIfQsY0", topic: "eliezer-yudkowsky", priority: 1 },
      { videoId: "tYINh16Bev4", topic: "gpt4", priority: 1 },
      { videoId: "c3bRNN5RJ5U", topic: "ilya-sutskever", priority: 1 },
      { videoId: "9ENJfet1lHU", topic: "garry-tan", priority: 2 },
      { videoId: "dNrTrx42N8M", topic: "george-hotz", priority: 2 },
      { videoId: "WAYS-ZHTkzo", topic: "balaji-srinivasan", priority: 2 },
      { videoId: "NbOq8UiKJe0", topic: "ari-emanuel", priority: 2 },
      { videoId: "3t25w27BvdE", topic: "stephen-wolfram", priority: 1 },
      { videoId: "DxREm3s61ok", topic: "kimbal-musk", priority: 2 },
      { videoId: "8rXD5yxPHy4", topic: "jeff-hawkins", priority: 2 },
      { videoId: "UxcO-UsMVYo", topic: "sam-harris", priority: 2 },
      { videoId: "G42RJ4m0YyI", topic: "robert-playter", priority: 2 },
      { videoId: "QJ9-ZKhQ7uE", topic: "geoffrey-hinton", priority: 1 },
      { videoId: "IdYYjKkxsB8", topic: "sam-altman", priority: 2 },
      { videoId: "c_cNGegc5zU", topic: "elon-musk", priority: 2 },
      { videoId: "wT8SZV9ogbE", topic: "elon-musk", priority: 2 },
      { videoId: "GvYYFloRy0o", topic: "jeff-dean", priority: 1 },
      { videoId: "QJ0fUmZSShE", topic: "elon-musk", priority: 2 },
      { videoId: "YRfjvgnFQx4", topic: "science", priority: 2 },
      { videoId: "fuejOk0OZBE", topic: "consciousness", priority: 2 },
      { videoId: "rLqwlQZX0KU", topic: "mathematics", priority: 2 },
      { videoId: "2i2fFBi9N3w", topic: "biology", priority: 2 },
      { videoId: "nF_YWdz6X5s", topic: "psychology", priority: 2 },
      { videoId: "3t2n5UtbnGY", topic: "cosmology", priority: 2 },
      { videoId: "rCauH7TFxjI", topic: "history", priority: 3 },
      { videoId: "MoPdEDu9-xI", topic: "neuroscience", priority: 2 },
      { videoId: "r-fwlvBuyzw", topic: "engineering", priority: 2 },
      { videoId: "KOwm7CTFn6c", topic: "robotics", priority: 2 },
      { videoId: "9ztaSRB3p8o", topic: "music", priority: 3 },
      { videoId: "7kFeJcDusMs", topic: "energy", priority: 2 },
      { videoId: "CdZN93LkyXc", topic: "physics", priority: 2 },
      { videoId: "Qc2BnGwQzkg", topic: "demis-hassabis", priority: 1 },
      { videoId: "1aA1WGNSsMo", topic: "free-speech", priority: 3 },
      { videoId: "MvYL6EeoUaI", topic: "jack-dorsey", priority: 2 },
      { videoId: "9NOkEhTNEjY", topic: "space", priority: 2 },
      { videoId: "L_Guz73e6fw", topic: "openai", priority: 1 },
      { videoId: "0jspaMLxBig", topic: "andrew-ng", priority: 1 },
      { videoId: "vif8NQcjVf0", topic: "jensen-huang", priority: 1 },
      { videoId: "-HzgcbRXUK8", topic: "demis-hassabis", priority: 1 },
      { videoId: "EV7WhVT270Q", topic: "state-of-ai-2026", priority: 1 },
      { videoId: "YFjfBk8HI5o", topic: "openclaw-ai-agent", priority: 1 },
      { videoId: "HsLgZzgpz9Y", topic: "dave-plummer", priority: 1 },
      { videoId: "vagyIcmIGOQ", topic: "dhh-programming", priority: 1 },
      { videoId: "HUkBz-cdB-k", topic: "terence-tao", priority: 1 },
      { videoId: "9V6tWC4CdFQ", topic: "sundar-pichai", priority: 1 },
      { videoId: "5t1vTLU7s40", topic: "guido-van-rossum", priority: 1 },
      { videoId: "mC43pZkpTec", topic: "dario-amodei", priority: 1 },
      { videoId: "cdiD-9MMpb0", topic: "andrej-karpathy", priority: 1 },
      { videoId: "Kbk9BiPhm7o", topic: "elon-musk-neuralink", priority: 1 },
      { videoId: "U5OD8MjYnOM", topic: "yann-lecun-2", priority: 1 },
      { videoId: "Qp0rCU49lMs", topic: "michael-levin", priority: 1 },
      { videoId: "NNr6gPelJ3E", topic: "roman-yampolskiy", priority: 1 },
      { videoId: "_1f-o0nqpEI", topic: "deepseek-openai-nvidia", priority: 1 },
      { videoId: "OHWnPOKh_S0", topic: "marc-andreessen", priority: 1 },
      { videoId: "e-gwvmhyU7A", topic: "aravind-srinivas", priority: 1 },
      { videoId: "F3Jd9GI6XqE", topic: "edward-gibson", priority: 1 },
      { videoId: "N1e7oyT0eVg", topic: "sam-altman-programming", priority: 1 },
      { videoId: "ffp4lu70fqQ", topic: "david-deutsch", priority: 1 },
      { videoId: "xBrNBfxVe8I", topic: "paul-graham", priority: 1 },
      { videoId: "SiHqnKFa5D4", topic: "sergey-brin", priority: 1 },
      { videoId: "rY-RP3u2tV8", topic: "jim-keller", priority: 1 },
      { videoId: "X9-nz8LWXFA", topic: "frank-wilczek", priority: 2 },
      { videoId: "jdjb-8h0acE", topic: "robert-playter-2", priority: 2 },
      { videoId: "zNkpwfeZBC4", topic: "dennis-ritchie-legacy", priority: 2 },
      { videoId: "8n_Cq8QdKUM", topic: "bjarne-stroustrup", priority: 1 },
      { videoId: "ORrWHULx4Lk", topic: "graham-hancock", priority: 3 },
      { videoId: "ZIYn6ABQtXA", topic: "roger-rees", priority: 3 },
      { videoId: "GF0IPbRtO8k", topic: "jimmy-wales", priority: 2 },
      { videoId: "1X0QPk2Jkn4", topic: "lee-cronin", priority: 2 },
      { videoId: "y3jYVe1RGaM", topic: "joscha-bach-2", priority: 1 },
      { videoId: "QVHeOGCs5sY", topic: "max-tegmark-2", priority: 1 },
      { videoId: "pNZWXmjv7P4", topic: "craig-venter", priority: 2 },
      { videoId: "13CZPWmke6A", topic: "donald-knuth-2", priority: 1 },
      { videoId: "acoSnDXUtIE", topic: "robert-playter-boston-dynamics", priority: 2 },
      { videoId: "wLgPk9k5DzQ", topic: "john-carmack-2", priority: 1 }
    ],
  },
  {
    slug: "dwarkesh-patel",
    name: "Dwarkesh Patel",
    category: "AI podcasts",
    videos: [
      { videoId: "is-O3mKdYFw", topic: "patrick-collison", priority: 1 },
      { videoId: "p8Jx4qvDoSo", topic: "sarah-paine", priority: 2 },
      { videoId: "tOtdJkpV2Vw", topic: "dario-amodei", priority: 1 },
      { videoId: "lXUZvyajciY", topic: "patrick-collison", priority: 2 },
      { videoId: "V979WdHSqO8", topic: "dario-amodei", priority: 1 },
      { videoId: "0jspaGHBaHA", topic: "sarah-paine", priority: 2 },
      { videoId: "x-ehJTxkQas", topic: "economics", priority: 2 },
      { videoId: "7gKJKHfqejA", topic: "ai-safety", priority: 2 },
      { videoId: "nis745H7YRc", topic: "scaling-laws", priority: 2 },
      { videoId: "2PXHZqv2-qc", topic: "ai-scaling-alignment", priority: 1 },
      { videoId: "bc6uFV9CJGg", topic: "mark-zuckerberg-llama", priority: 1 },
      { videoId: "aR20FWCCjAs", topic: "ilya-sutskever", priority: 1 },
      { videoId: "n1E9IZfvGMA", topic: "dario-amodei-exponential", priority: 1 },
      { videoId: "Hrbq66XqtCo", topic: "jensen-huang-moat", priority: 1 },
      { videoId: "xmkSf5IS-zw", topic: "how-llms-trained", priority: 1 },
      { videoId: "21EYKqUsPfg", topic: "richard-sutton", priority: 1 },
      { videoId: "8-boBsWcr5A", topic: "satya-nadella", priority: 1 },
      { videoId: "BYXbuik3dgA", topic: "elon-musk-space", priority: 1 },
      { videoId: "_9V_Hbe-N1A", topic: "adam-marblestone", priority: 1 },
      { videoId: "Q8Fkpi18QXU", topic: "terence-tao", priority: 1 },
      { videoId: "48pxVdmkMIE", topic: "sergey-levine", priority: 1 },
      { videoId: "3cDHx2_QbPE", topic: "china-energy-agi", priority: 1 },
      { videoId: "mDG_Hx3BSUE", topic: "dylan-patel-compute", priority: 1 },
      { videoId: "myP8UjAM1pk", topic: "michael-nielsen", priority: 1 }
    ],
  },
  {
    slug: "andrej-karpathy",
    name: "Andrej Karpathy",
    category: "AI podcasts",
    videos: [
      { videoId: "kCc8FmEb1nY", topic: "large-language-models", priority: 1 },
      { videoId: "LWiM-LuRe6Q", topic: "neural-networks", priority: 1 },
      { videoId: "u1wT0mEurCU", topic: "gpt", priority: 1 },
      { videoId: "VMj-3S1tUxc", topic: "makemore", priority: 1 }
    ],
  },
  {
    slug: "ai-explained",
    name: "AI Explained",
    category: "AI podcasts",
    videos: [
      { videoId: "h1AzMaWYkmg", topic: "ai-news", priority: 2 }
    ],
  },
  {
    slug: "openai",
    name: "OpenAI",
    category: "AI podcasts",
    videos: [
      { videoId: "wbEk6mIlDMc", topic: "devday", priority: 1 }
    ],
  },
  {
    slug: "stanford",
    name: "Stanford",
    category: "AI podcasts",
    videos: [
      { videoId: "p0FERNkpyHE", topic: "sam-altman", priority: 1 }
    ],
  },
  {
    slug: "hard-fork",
    name: "Hard Fork",
    category: "AI podcasts",
    videos: [
      { videoId: "5MWT_doo68k", topic: "tech-news", priority: 2 }
    ],
  },
  {
    slug: "no-priors",
    name: "No Priors",
    category: "AI podcasts",
    videos: [
      { videoId: "HAn9sNAJLHQ", topic: "venture-ai", priority: 2 }
    ],
  },
  {
    slug: "a16z",
    name: "a16z",
    category: "AI podcasts",
    videos: [
      { videoId: "6_1QLHugH3c", topic: "ai-startups", priority: 2 }
    ],
  },
  {
    slug: "y-combinator",
    name: "Y Combinator",
    category: "AI podcasts",
    videos: [
      { videoId: "Z1Lufu0FSrI", topic: "ai-startup-school", priority: 2 }
    ],
  },
  {
    slug: "y-combinator",
    name: "Y Combinator",
    category: "business interviews",
    videos: [
      { videoId: "CBYhVc0glP8", topic: "startup-advice", priority: 1 },
      { videoId: "CnE3V9ZPyhk", topic: "founder-stories", priority: 1 },
      { videoId: "GYl6WpV3FoU", topic: "saas", priority: 1 },
      { videoId: "T9ikpoF2GH0", topic: "fundraising", priority: 1 },
      { videoId: "V993GZwcS-c", topic: "product-market-fit", priority: 1 },
      { videoId: "St5fVtlDI_Q", topic: "b2b-sales", priority: 2 },
      { videoId: "6WtdFqgsEY0", topic: "hiring", priority: 2 },
      { videoId: "XsZSxXU4-qQ", topic: "pivoting", priority: 2 },
      { videoId: "hF515-0TQk4", topic: "startup-playbook", priority: 1 },
      { videoId: "4aQAgAjTozk", topic: "founder-mode", priority: 1 },
      { videoId: "IACHfKm9Mow", topic: "yc-interview", priority: 2 },
      { videoId: "MT4Ig2uqjTc", topic: "customer-discovery", priority: 1 },
      { videoId: "Th8JoIan4dg", topic: "startup-ideas", priority: 2 }
    ],
  },
  {
    slug: "diary-of-a-ceo",
    name: "Diary of a CEO",
    category: "business interviews",
    videos: [
      { videoId: "zQctEb0JyYc", topic: "entrepreneurship", priority: 1 },
      { videoId: "NbDgg22f0B0", topic: "leadership", priority: 1 },
      { videoId: "b67LiRvIDBc", topic: "founder-mindset", priority: 1 }
    ],
  },
  {
    slug: "my-first-million",
    name: "My First Million",
    category: "business interviews",
    videos: [
      { videoId: "F9LWUVJeGxw", topic: "startup-ideas", priority: 2 },
      { videoId: "oWZbWzAyHAE", topic: "business-growth", priority: 2 }
    ],
  },
  {
    slug: "gary-vaynerchuk",
    name: "Gary Vaynerchuk",
    category: "business interviews",
    videos: [
      { videoId: "d0yGdNEWdn0", topic: "marketing", priority: 2 }
    ],
  },
  {
    slug: "harvard-i-lab",
    name: "Harvard i-lab",
    category: "business interviews",
    videos: [
      { videoId: "G3e-cpL7ofc", topic: "entrepreneurship", priority: 2 }
    ],
  },
  {
    slug: "stanford",
    name: "Stanford",
    category: "business interviews",
    videos: [
      { videoId: "UF8uR6Z6KLc", topic: "steve-jobs", priority: 1 }
    ],
  },
  {
    slug: "stanford-ecorner",
    name: "Stanford eCorner",
    category: "business interviews",
    videos: [
      { videoId: "7bB__8O9Y8c", topic: "startup-lessons", priority: 2 }
    ],
  },
  {
    slug: "the-plain-bagel",
    name: "The Plain Bagel",
    category: "finance education",
    videos: [
      { videoId: "8VGHIH5FBA8", topic: "investing-basics", priority: 1 },
      { videoId: "TJDcN3pm4us", topic: "stock-market", priority: 1 },
      { videoId: "IjnRJXPct1k", topic: "index-funds", priority: 1 },
      { videoId: "wX8fWXefGLc", topic: "passive-investing", priority: 2 }
    ],
  },
  {
    slug: "graham-stephan",
    name: "Graham Stephan",
    category: "finance education",
    videos: [
      { videoId: "lNdOtlpmH5U", topic: "personal-finance", priority: 1 },
      { videoId: "9R_SaLH1lOc", topic: "real-estate", priority: 2 },
      { videoId: "hJnw3TQXNDs", topic: "housing-market", priority: 2 }
    ],
  },
  {
    slug: "whiteboard-finance",
    name: "Whiteboard Finance",
    category: "finance education",
    videos: [
      { videoId: "UZBKE1b2tMI", topic: "investing", priority: 1 }
    ],
  },
  {
    slug: "khan-academy",
    name: "Khan Academy",
    category: "finance education",
    videos: [
      { videoId: "gw6Llagaa4o", topic: "finance-intro", priority: 1 },
      { videoId: "rD6L2FmvduI", topic: "compound-interest", priority: 1 },
      { videoId: "WEDIj9JBTCk", topic: "personal-finance", priority: 2 }
    ],
  },
  {
    slug: "ray-dalio",
    name: "Ray Dalio",
    category: "finance education",
    videos: [
      { videoId: "wjc7FzeD7gg", topic: "economic-principles", priority: 1 },
      { videoId: "6Zr0v5q2e7U", topic: "debt-cycles", priority: 2 },
      { videoId: "B9XG_upIDOE", topic: "economic-cycles", priority: 1 }
    ],
  },
  {
    slug: "warren-buffett",
    name: "Warren Buffett",
    category: "finance education",
    videos: [
      { videoId: "TMF1I-9NVOw", topic: "investing-wisdom", priority: 1 },
      { videoId: "2MhiHBFMoUk", topic: "value-investing", priority: 1 }
    ],
  },
  {
    slug: "andrew-huberman",
    name: "Andrew Huberman",
    category: "self-improvement podcasts",
    videos: [
      { videoId: "4HiueBzp2w8", topic: "dopamine", priority: 1 },
      { videoId: "w42a_LeP4FY", topic: "motivation", priority: 1 },
      { videoId: "K1ng2KVDlzE", topic: "caffeine", priority: 2 },
      { videoId: "1gmpCIuo-vA", topic: "fitness", priority: 1 },
      { videoId: "ozHwx-jsF-w", topic: "cold-exposure", priority: 2 },
      { videoId: "7CKVpHv5Y-k", topic: "stress", priority: 1 },
      { videoId: "UZMUPw8pP0o", topic: "meditation", priority: 2 },
      { videoId: "y3Umo_jd5AA", topic: "learning", priority: 2 },
      { videoId: "hFL6qRIJZ_Y", topic: "focus", priority: 1 },
      { videoId: "nm1TxQj9IsQ", topic: "sleep", priority: 1 }
    ],
  },
  {
    slug: "tim-ferriss",
    name: "Tim Ferriss",
    category: "self-improvement podcasts",
    videos: [
      { videoId: "eB2LUXaSOfU", topic: "performance", priority: 1 },
      { videoId: "QmOF0crdyRU", topic: "productivity", priority: 2 }
    ],
  },
  {
    slug: "naval-ravikant",
    name: "Naval Ravikant",
    category: "self-improvement podcasts",
    videos: [
      { videoId: "TAKErg_Duk4", topic: "happiness", priority: 1 }
    ],
  },
  {
    slug: "jay-shetty",
    name: "Jay Shetty",
    category: "self-improvement podcasts",
    videos: [
      { videoId: "3qHkc9OOzcQ", topic: "habits", priority: 2 }
    ],
  },
  {
    slug: "jocko-willink",
    name: "Jocko Willink",
    category: "self-improvement podcasts",
    videos: [
      { videoId: "6ZrlsVx85ek", topic: "discipline", priority: 1 }
    ],
  },
  {
    slug: "cal-newport",
    name: "Cal Newport",
    category: "self-improvement podcasts",
    videos: [
      { videoId: "ktiZ5j4QO0A", topic: "deep-work", priority: 1 }
    ],
  },
  {
    slug: "james-clear",
    name: "James Clear",
    category: "self-improvement podcasts",
    videos: [
      { videoId: "l7FSOuFnWRo", topic: "atomic-habits", priority: 1 }
    ],
  },
  {
    slug: "corey-schafer",
    name: "Corey Schafer",
    category: "programming tutorials",
    videos: [
      { videoId: "HGOBQPFzWKo", topic: "terminal", priority: 2 },
      { videoId: "eWRfhZUzrAc", topic: "python", priority: 2 },
      { videoId: "7wnove7K-ZQ", topic: "python", priority: 2 },
      { videoId: "fKl2JW_qrso", topic: "django", priority: 1 },
      { videoId: "UmljXZIypDc", topic: "django", priority: 2 },
      { videoId: "HGoYwMBk6a8", topic: "python-oop", priority: 1 },
      { videoId: "DZtn3fDLMTA", topic: "python-decorators", priority: 2 },
      { videoId: "Da-2h2B4fbU", topic: "flask", priority: 1 },
      { videoId: "jBzwzrDvZbc", topic: "python", priority: 2 },
      { videoId: "N5vscRTVt7M", topic: "django", priority: 2 },
      { videoId: "c4M26jsVr70", topic: "django", priority: 2 },
      { videoId: "Z1RJmh_OqeA", topic: "flask-tutorial", priority: 1 },
      { videoId: "iukOehU5aF4", topic: "fastapi", priority: 1 },
      { videoId: "TEb0Zc0b10U", topic: "matplotlib", priority: 2 },
      { videoId: "uixAmdJatXc", topic: "argparse", priority: 2 },
      { videoId: "eKqGTln-PuY", topic: "virtual-environments", priority: 2 },
      { videoId: "t8pYpRWdspE", topic: "docker", priority: 2 },
      { videoId: "JIf9COiNlqc", topic: "git", priority: 2 },
      { videoId: "e41ZvEdHxj0", topic: "sqlalchemy", priority: 2 },
      { videoId: "3c8zFpEsvsY", topic: "context-managers", priority: 2 },
      { videoId: "KlBPCzcQyl8", topic: "logging", priority: 2 },
      { videoId: "ve2pmmVJ2n0", topic: "regex", priority: 2 },
      { videoId: "NI26aqiae_E", topic: "beautifulsoup", priority: 2 },
      { videoId: "rq8cLfkQxOg", topic: "file-io", priority: 2 },
      { videoId: "6iIsz1AYnK8", topic: "csv-json", priority: 2 },
      { videoId: "v3NHysI4l8k", topic: "multiprocessing", priority: 2 },
      { videoId: "W8KRzm-HUcc", topic: "threading", priority: 2 },
      { videoId: "nhBVL41-_W4", topic: "itertools", priority: 2 },
      { videoId: "K5KVE_wzCgk", topic: "functools", priority: 2 }
    ],
  },
  {
    slug: "3blue1brown",
    name: "3Blue1Brown",
    category: "programming tutorials",
    videos: [
      { videoId: "aircAruvnKk", topic: "neural-networks", priority: 1 },
      { videoId: "IHZwWFHWa-w", topic: "linear-algebra", priority: 1 },
      { videoId: "jGw_UM8cfgA", topic: "neural-networks", priority: 1 },
      { videoId: "4Wrcu6BdhXg", topic: "essence-linear-algebra", priority: 1 },
      { videoId: "kjBOesHnagY", topic: "essence-calculus", priority: 1 },
      { videoId: "Ilg3gGewQ5U", topic: "backpropagation", priority: 1 },
      { videoId: "tIeHLJnJ6IY", topic: "gradient-descent", priority: 1 }
    ],
  },
  {
    slug: "stanford-online",
    name: "Stanford Online",
    category: "AI podcasts",
    videos: [
      { videoId: "PaCmpygFfXo", topic: "computer-vision", priority: 1 },
      { videoId: "PySo_6S4ZAg", topic: "transformers", priority: 1 },
      { videoId: "4PaBNEd6SR4", topic: "nlp", priority: 1 },
      { videoId: "vT1Zj5rWpYM", topic: "cs224n", priority: 1 },
      { videoId: "MNIwwo_nZpY", topic: "deep-learning", priority: 1 },
      { videoId: "rmVRLeJRkl4", topic: "cs224n-lecture-1", priority: 1 },
      { videoId: "6g4O5UOH304", topic: "cs229-logistic-regression", priority: 1 },
      { videoId: "h0e2HAPTGF4", topic: "cs229-naive-bayes", priority: 1 },
      { videoId: "TjZBTDzGeGg", topic: "cs229-policy-gradient", priority: 1 },
      { videoId: "vT1JzLTH4G4", topic: "cs231n-cnn-intro", priority: 1 },
      { videoId: "j3N6eRt7SPs", topic: "cs231n-backprop", priority: 1 },
      { videoId: "dXEbbbQ51eA", topic: "cs231n-neural-nets", priority: 1 },
      { videoId: "AwHTNEJ81rI", topic: "cs231n-cnn-architectures", priority: 1 },
      { videoId: "8dGs36Fo_WE", topic: "cs224n-word2vec", priority: 1 },
      { videoId: "9vM4p9NN0Ts", topic: "cs224n-glove", priority: 1 },
      { videoId: "nFTQ7k7U4xU", topic: "cs224n-rnn", priority: 1 },
      { videoId: "BJjjOWqGXPs", topic: "cs224n-seq2seq", priority: 1 },
      { videoId: "PYHFIZU9sEs", topic: "cs330-deep-rl", priority: 1 },
      { videoId: "4Bdc55j80l8", topic: "cs229-svm", priority: 1 },
      { videoId: "ktxecZ3JkO0", topic: "cs229-kernel-methods", priority: 1 },
      { videoId: "ptuGllU5SQQ", topic: "cs224n-overview", priority: 1 },
      { videoId: "noQEvlHAUAE", topic: "cs224n-word-vectors", priority: 1 },
      { videoId: "iWONvLMUE7E", topic: "cs231n-overview", priority: 1 },
      { videoId: "FScyHcZLVR8", topic: "cs25-transformers", priority: 1 },
      { videoId: "4Xfi23Yfn-U", topic: "cs229-intro", priority: 1 }
    ],
  },
  {
    slug: "deeplearning.ai",
    name: "DeepLearning.AI",
    category: "AI podcasts",
    videos: [
      { videoId: "7xTGNNLPyMI", topic: "deep-learning", priority: 1 },
      { videoId: "4b4MUYve_U8", topic: "machine-learning", priority: 2 },
      { videoId: "M7grwLR7w4M", topic: "andrew-ng-ml-specialization", priority: 1 }
    ],
  },
  {
    slug: "yannic-kilcher",
    name: "Yannic Kilcher",
    category: "AI podcasts",
    videos: [
      { videoId: "CDiqA4SJNpA", topic: "machine-learning", priority: 2 },
      { videoId: "eyxmSmjmNS0", topic: "gan-paper", priority: 1 },
      { videoId: "TrdevFK_am4", topic: "vit-paper", priority: 1 },
      { videoId: "jE9jAZC42NE", topic: "rnns-paper", priority: 1 },
      { videoId: "iDulhoQ2pro", topic: "bert-paper", priority: 1 },
      { videoId: "zjkBMFhNj_g", topic: "gpt3-paper", priority: 1 },
      { videoId: "9uw3F6rndnA", topic: "clip-paper", priority: 1 },
      { videoId: "bZQun8Y4L2A", topic: "rlhf-paper", priority: 1 },
      { videoId: "9zKuYvjFFS8", topic: "gpt4-system-card", priority: 1 },
      { videoId: "9-Jl0dxWQs8", topic: "mamba-paper", priority: 1 },
      { videoId: "bAWV_yrqx4w", topic: "grpo-deepseekmath", priority: 1 },
      { videoId: "hpC4qjWu_aY", topic: "context-rot", priority: 1 },
      { videoId: "RAEy3JZmIaA", topic: "energy-based-transformers", priority: 1 },
      { videoId: "V71AJoYAtBQ", topic: "biology-of-llm", priority: 1 },
      { videoId: "AfAmwIP2ntY", topic: "test-time-compute", priority: 1 },
      { videoId: "B45FlSQ8ITo", topic: "matmul-free-lm", priority: 1 },
      { videoId: "7NNxK3CqaDk", topic: "flow-matching", priority: 1 },
      { videoId: "loaTGpqfctI", topic: "byte-latent-transformer", priority: 1 },
      { videoId: "gfU5y7qCxF0", topic: "tokenformer", priority: 1 },
      { videoId: "Bs6eyNQjGpo", topic: "gsm-symbolic", priority: 1 },
      { videoId: "WwbukAcMM4k", topic: "privacy-backdoors", priority: 1 },
      { videoId: "-r0XPC7TLzY", topic: "safety-alignment", priority: 1 },
      { videoId: "0OaEv1a5jUM", topic: "xlstm", priority: 1 },
      { videoId: "3a0_hAiFKag", topic: "transformerfam", priority: 1 },
      { videoId: "52kMBrAI_IM", topic: "orpo", priority: 1 },
      { videoId: "Nao16-6l6dQ", topic: "free-transformer-vae", priority: 1 },
      { videoId: "PW4JiJ-WaY4", topic: "planning-transformers", priority: 1 },
      { videoId: "kzB23CoZG30", topic: "ml-news-llama-3", priority: 2 },
      { videoId: "dnTGn1EQqtQ", topic: "ml-news-gtc", priority: 2 },
      { videoId: "5bPBbQyLI7E", topic: "ml-news-gpt4o", priority: 2 },
      { videoId: "YOyr9Bhhaq0", topic: "ml-news-elon-openai", priority: 2 },
      { videoId: "3nF8Z6HgSLQ", topic: "ml-news-groq-gemma", priority: 2 },
      { videoId: "Kk8YhCpo1b8", topic: "ml-news-jamba", priority: 2 }
    ],
  },
  {
    slug: "the-net-ninja",
    name: "The Net Ninja",
    category: "programming tutorials",
    videos: [
      { videoId: "ItZ2TmIj40U", topic: "javascript", priority: 1 },
      { videoId: "iLBT0lOdLFQ", topic: "vue", priority: 1 },
      { videoId: "YrxBCB_bVgM", topic: "nuxt", priority: 2 },
      { videoId: "bi5vhY9CLfw", topic: "vuex", priority: 2 },
      { videoId: "3aS1KRz_Z9k", topic: "tailwind", priority: 1 },
      { videoId: "j942wKiXFu8", topic: "react-series", priority: 1 },
      { videoId: "iWOYAxlnaww", topic: "modern-javascript", priority: 1 },
      { videoId: "hu-q2zYwEYs", topic: "html-css-series", priority: 1 },
      { videoId: "wqjNeSTu7ik", topic: "react-hooks", priority: 1 },
      { videoId: "OxTGwZ5l5J8", topic: "firebase", priority: 1 },
      { videoId: "KnHAuw2VIxY", topic: "nextjs", priority: 1 },
      { videoId: "o3PtCE0wyvw", topic: "supabase", priority: 1 },
      { videoId: "xiHn38lqKU4", topic: "flutter", priority: 2 },
      { videoId: "jR4fDIATj8E", topic: "vue-3", priority: 1 },
      { videoId: "q8cf5nhihZU", topic: "graphql", priority: 2 },
      { videoId: "6Xx2kSEusjU", topic: "node-express", priority: 1 },
      { videoId: "ZBK3K9rKqa8", topic: "mongodb", priority: 1 },
      { videoId: "y285yddQJ5Q", topic: "typescript", priority: 1 },
      { videoId: "QQ3k0Xn9Y9Q", topic: "react-redux", priority: 2 }
    ],
  },
  {
    slug: "stanford-online",
    name: "Stanford Online",
    category: "programming tutorials",
    videos: [
      { videoId: "6xTHwMtNq_Y", topic: "machine-learning", priority: 1 }
    ],
  },
  {
    slug: "fireship",
    name: "Fireship",
    category: "programming tutorials",
    videos: [
      { videoId: "Tn6-PIqc4UM", topic: "react", priority: 2 }
    ],
  },
  {
    slug: "mit-opencourseware",
    name: "MIT OpenCourseWare",
    category: "finance education",
    videos: [
      { videoId: "ZK3O402wf1c", topic: "linear-algebra", priority: 3 }
    ],
  },
  {
    slug: "google-developers",
    name: "Google Developers",
    category: "programming tutorials",
    videos: [
      { videoId: "jGwOUGg-jCw", topic: "tensorflow-ml-crash", priority: 1 },
      { videoId: "3dojXA_ihKk", topic: "machine-learning-intro", priority: 1 },
      { videoId: "nQS_jrD8Hsk", topic: "kotlin-android", priority: 1 },
      { videoId: "7KPVp7hIGfc", topic: "google-cloud-essentials", priority: 2 },
      { videoId: "Gjnup-Puqu0", topic: "firebase-web", priority: 2 },
      { videoId: "lTTajzrSkBw", topic: "chrome-devtools", priority: 2 }
    ],
  },
  {
    slug: "sentdex",
    name: "sentdex",
    category: "programming tutorials",
    videos: [
      { videoId: "eE5UswtOIfU", topic: "machine-learning-python", priority: 1 },
      { videoId: "OGxgnH8y2GQ", topic: "neural-networks-python", priority: 1 },
      { videoId: "vI3MHF9ZYpQ", topic: "tensorflow-python", priority: 1 },
      { videoId: "wQ8BIBpyS2g", topic: "matplotlib", priority: 2 },
      { videoId: "Z78IQMbkWqU", topic: "pandas", priority: 2 }
    ],
  },
  {
    slug: "nvidia",
    name: "NVIDIA",
    category: "AI podcasts",
    videos: [
      { videoId: "lIjzF3T2B7Y", topic: "gtc-keynote-ai", priority: 1 },
      { videoId: "ScsppLKBLkg", topic: "generative-ai-explained", priority: 1 }
    ],
  },
  {
    slug: "twiml-ai",
    name: "TWIML AI",
    category: "AI podcasts",
    videos: [
      { videoId: "5A0qAYKxbH8", topic: "andrew-ng-interview", priority: 1 },
      { videoId: "Q7r--DqG0lk", topic: "yann-lecun-interview", priority: 1 },
      { videoId: "8F5QdAtUJPg", topic: "demis-hassabis-interview", priority: 1 },
      { videoId: "0VH1LimQ4So", topic: "ilya-sutskever-interview", priority: 1 },
      { videoId: "V1eYniV1ooM", topic: "geoffrey-hinton-interview", priority: 1 },
      { videoId: "u6XAPnuFjJc", topic: "sam-altman-interview", priority: 1 }
    ],
  },
  {
    slug: "latent-space",
    name: "Latent Space",
    category: "AI podcasts",
    videos: [
      { videoId: "rb2oJxOZnnE", topic: "ai-engineering-podcast", priority: 1 },
      { videoId: "SWfHxVAfHGk", topic: "llm-agents", priority: 1 },
      { videoId: "uRu3zHnWPdg", topic: "rag-production", priority: 1 }
    ],
  },
  {
    slug: "berkeley-cs61a",
    name: "Berkeley CS61A",
    category: "programming tutorials",
    videos: [
      { videoId: "0_LryzvBxFw", topic: "cs61a-lecture-1", priority: 1 },
      { videoId: "8m01DTjUg78", topic: "cs61a-lecture-2", priority: 1 },
      { videoId: "ENY0tbFlccY", topic: "cs61a-lecture-3", priority: 1 },
      { videoId: "HmL0E-viG4c", topic: "cs61a-lecture-4", priority: 1 },
      { videoId: "q6iqI2GIllI", topic: "cs61a-higher-order", priority: 1 },
      { videoId: "x4sQkFYW0-0", topic: "cs61a-recursion", priority: 1 },
      { videoId: "Lgy92S0xXC4", topic: "cs61a-trees", priority: 1 }
    ],
  },
  {
    slug: "android-developers",
    name: "Android Developers",
    category: "programming tutorials",
    videos: [
      { videoId: "LcrTYsHHhqM", topic: "kotlin-fundamentals", priority: 1 },
      { videoId: "F9UC9DY-vIU", topic: "android-architecture", priority: 1 },
      { videoId: "0SJE9dYdpps", topic: "material-design", priority: 2 }
    ],
  },
  {
    slug: "ibm-technology",
    name: "IBM Technology",
    category: "programming tutorials",
    videos: [
      { videoId: "Ok-xpKjKp2g", topic: "kubernetes-explained", priority: 1 },
      { videoId: "1xo-0-kc2EI", topic: "microservices-explained", priority: 1 },
      { videoId: "kv1MXVZ3890", topic: "blockchain-explained", priority: 2 },
      { videoId: "yubzJw0uiE4", topic: "ai-explained", priority: 1 }
    ],
  },
  {
    slug: "mongodb-university",
    name: "MongoDB University",
    category: "programming tutorials",
    videos: [
      { videoId: "Www6koajkGw", topic: "mongodb-basics", priority: 1 },
      { videoId: "ofme2EUyX8w", topic: "mongodb-aggregation", priority: 2 }
    ],
  },
];

export const SEED_CHANNEL_CATEGORIES = [...new Set(SEED_CHANNEL_CATALOG.map((channel) => channel.category))];
