export type SeedChannelVideo = {
  videoId: string;
  topic: string;
  priority: number;
};

export type SeedChannel = {
  slug: string;
  name: string;
  category: string;
  videos: SeedChannelVideo[];
};

export const SEED_CHANNEL_CATALOG: SeedChannel[] = [
  {
    slug: "freecodecamp",
    name: "freeCodeCamp",
    category: "programming tutorials",
    videos: [
      { videoId: "eIrMbAQqh4Q", topic: "java", priority: 1 },
      { videoId: "bMknfKXYPfb", topic: "react", priority: 1 },
      { videoId: "Oe421EPjBEg", topic: "nodejs", priority: 1 },
      { videoId: "RBSGKlAvoiM", topic: "data-structures", priority: 1 },
      { videoId: "HXV3zeQKq0E", topic: "sql", priority: 1 },
      { videoId: "N4VDN1jhg2U", topic: "git", priority: 1 },
      { videoId: "kqtD5kpI9F0", topic: "cpp", priority: 1 },
      { videoId: "mU6anWqZJcc", topic: "responsive-design", priority: 1 },
      { videoId: "8ext9G7xspg", topic: "golang", priority: 2 },
      { videoId: "8jLOx1hD3_o", topic: "csharp", priority: 1 },
      { videoId: "w7ejDZ8SWv8", topic: "react-native", priority: 2 },
      { videoId: "TBoSDECjPSY", topic: "expressjs", priority: 2 },
      { videoId: "1Rs2ND1ryYc", topic: "css", priority: 1 },
      { videoId: "fqMOXHJfhYk", topic: "docker", priority: 1 },
      { videoId: "t8pPdKYpowI", topic: "kotlin", priority: 2 },
      { videoId: "nu_pCVPKzTk", topic: "fullstack-javascript", priority: 1 },
      { videoId: "3PHXvlpOkfE", topic: "nextjs", priority: 1 },
      { videoId: "41-qW0nQ5gQ", topic: "svelte", priority: 2 },
      { videoId: "gXLjWRteuWI", topic: "rust", priority: 1 },
      { videoId: "8JJ101D3knE", topic: "git-github", priority: 2 },
      { videoId: "yaqe1qesAJ8", topic: "dynamic-programming", priority: 2 },
      { videoId: "2ISbhNrSalI", topic: "cs50-week1", priority: 1 },
      { videoId: "KJgsSFOSQv0", topic: "c-programming", priority: 1 },
      { videoId: "zY02NjoXK7k", topic: "php", priority: 2 },
      { videoId: "9cKsq14Kfsw", topic: "mongodb", priority: 1 },
      { videoId: "i_LwzRVP7bg", topic: "bootstrap", priority: 2 },
      { videoId: "2ybLD6_2gKM", topic: "seo", priority: 3 },
      { videoId: "qIsgdOVGA04", topic: "excel", priority: 2 },
      { videoId: "gB1F9G0JXOo", topic: "unreal-engine", priority: 2 },
      { videoId: "B31LgI4Y4DQ", topic: "terraform", priority: 1 },
      { videoId: "3c-iBn73dDE", topic: "aws", priority: 1 },
      { videoId: "HkvKkDpt0hs", topic: "django", priority: 1 },
      { videoId: "xWi8n2DQX2k", topic: "laravel", priority: 1 },
      { videoId: "GoCF3RLr7b8", topic: "spring-boot", priority: 1 },
      { videoId: "PZ7lDRQJroe", topic: "flask", priority: 1 },
      { videoId: "pQRNCAgH5Jg", topic: "bootstrap", priority: 2 },
      { videoId: "9kkem8v-8Z0", topic: "linux", priority: 1 },
      { videoId: "3YS713M0aek", topic: "cybersecurity", priority: 1 },
      { videoId: "BI1Ak2DJ9yk", topic: "ethical-hacking", priority: 2 },
      { videoId: "AwesGL0cnF0", topic: "ui-ux", priority: 2 },
      { videoId: "9zKGFVTMF-M", topic: "blender", priority: 3 },
      { videoId: "7SnyY0KTUcg", topic: "data-analysis", priority: 1 },
      { videoId: "LfaMVlDaE5c", topic: "power-bi", priority: 2 },
      { videoId: "CLLTZTU8tuo", topic: "tableau", priority: 2 },
      { videoId: "FgzE3v6sv0U", topic: "bootstrap", priority: 2 },
      { videoId: "pTFZFgx4IbM", topic: "flutter", priority: 1 },
      { videoId: "VPvVD8t02Z8", topic: "flutter", priority: 2 },
      { videoId: "wN0Vc7-redY", topic: "csharp", priority: 1 },
      { videoId: "qB2U2eWx3uA", topic: "unity", priority: 2 },
      { videoId: "G_EptEUsIkw", topic: "angular", priority: 1 },
      { videoId: "2qQWl9H3Y1s", topic: "swift", priority: 1 },
      { videoId: "pE0a4KnSE22", topic: "kotlin-android", priority: 2 },
      { videoId: "1Xj73ygVVoo", topic: "react-native", priority: 2 },
      { videoId: "SLB4Z5VoWNE", topic: "kubernetes", priority: 1 },
      { videoId: "jZdaM2OLfmQ", topic: "git-github", priority: 2 },
      { videoId: "zJch2fphYYA", topic: "devops", priority: 2 },
      { videoId: "nu6mMF4BgOI", topic: "postgresql", priority: 1 },
      { videoId: "QIyk-gU9b18", topic: "redis", priority: 2 },
      { videoId: "1PnVq36WuJE", topic: "ruby", priority: 2 },
      { videoId: "vp9sH8kPL88", topic: "elixir", priority: 3 },
      { videoId: "9z12uzaicRw", topic: "scala", priority: 3 },
      { videoId: "1W3yy0YJpjE", topic: "haskell", priority: 3 },
      { videoId: "1OALW-RrRVk", topic: "assembly", priority: 3 },
      { videoId: "M8HrtodtpL4", topic: "blockchain", priority: 2 },
      { videoId: "PkZNo7MFNFg", topic: "javascript", priority: 1 },
      { videoId: "rfscVS0vtbw", topic: "python", priority: 1 },
    ],
  },
  {
    slug: "mit-opencourseware",
    name: "MIT OpenCourseWare",
    category: "programming tutorials",
    videos: [
      { videoId: "VyWAvY2CF9c", topic: "algorithms", priority: 1 },
      { videoId: "2ePf9rue1Ao", topic: "algorithms", priority: 1 },
      { videoId: "WUvTyaaNkzM", topic: "mathematics", priority: 2 },
      { videoId: "70bSF1MN8fk", topic: "computer-science", priority: 1 },
      { videoId: "W5J5JHal5-c", topic: "algorithms", priority: 2 },
      { videoId: "nBuS-WjidY8", topic: "linear-algebra", priority: 1 },
    ],
  },
  {
    slug: "harvard-cs50",
    name: "Harvard CS50",
    category: "programming tutorials",
    videos: [
      { videoId: "8mAITcNt710", topic: "artificial-intelligence", priority: 1 },
      { videoId: "5q87K1WaoDR", topic: "python", priority: 1 },
    ],
  },
  {
    slug: "programming-with-mosh",
    name: "Programming with Mosh",
    category: "programming tutorials",
    videos: [
      { videoId: "W6NZfCO5XIk", topic: "javascript-basics", priority: 1 },
      { videoId: "SqcY0GlETPk", topic: "typescript", priority: 1 },
      { videoId: "_uQrJ0TkZlc", topic: "python-basics", priority: 1 },
    ],
  },
  {
    slug: "traversy-media",
    name: "Traversy Media",
    category: "programming tutorials",
    videos: [
      { videoId: "C5Q76MPdcgQ", topic: "nodejs-crash-course", priority: 2 },
      { videoId: "hdI2bqOjy3c", topic: "javascript", priority: 2 },
      { videoId: "PoRJizFvM7s", topic: "react", priority: 1 },
      { videoId: "3q1t5YcUAb8", topic: "mern-stack", priority: 1 },
      { videoId: "bkV9g5LtSgk", topic: "python", priority: 2 },
      { videoId: "yDJCDHA5ni0", topic: "react-hooks", priority: 1 },
      { videoId: "OFS90tXvk9Q", topic: "javascript", priority: 1 },
      { videoId: "4UZrsTqkcTI", topic: "nextjs", priority: 1 },
      { videoId: "SBmSRk3Feww", topic: "vue", priority: 1 },
      { videoId: "Ke90YMEj5kY", topic: "mongodb", priority: 2 },
    ],
  },
  {
    slug: "lex-fridman",
    name: "Lex Fridman",
    category: "AI podcasts",
    videos: [
      { videoId: "uX9W5DglMow", topic: "elon-musk", priority: 1 },
      { videoId: "gk4tEO4jDUM", topic: "sadhguru", priority: 2 },
      { videoId: "jfqwHT3QgWQ", topic: "jordan-peterson", priority: 2 },
      { videoId: "nzfMk4LBRmQ", topic: "turing-award", priority: 1 },
      { videoId: "vjMqTEbi9Vo", topic: "nvidia", priority: 1 },
      { videoId: "tYrdA4GiiBw", topic: "mark-zuckerberg", priority: 1 },
      { videoId: "-wx-vm4z5gs", topic: "robert-greene", priority: 2 },
      { videoId: "Whtt2H5_isM", topic: "max-tegmark", priority: 1 },
      { videoId: "mwKJfNYwvm8", topic: "eric-weinstein", priority: 2 },
      { videoId: "Q0nGo2-y0xY", topic: "donald-knuth", priority: 1 },
      { videoId: "JN3KPFbWCy8", topic: "elon-musk", priority: 2 },
      { videoId: "jvqFAi7vkBc", topic: "elon-musk", priority: 2 },
      { videoId: "rIpUf-Vy2JA", topic: "richard-feynman", priority: 2 },
      { videoId: "Z3_PwvvfxIU", topic: "programming", priority: 2 },
      { videoId: "SGSOCuByo24", topic: "space-exploration", priority: 2 },
      { videoId: "P6prRXkI5HM", topic: "literature", priority: 3 },
      { videoId: "XkY2DOUCWMU", topic: "jeff-bezos", priority: 2 },
      { videoId: "sY8-YISYpVu", topic: "demis-hassabis", priority: 1 },
      { videoId: "mC43CHIhjTQ", topic: "andrew-ng", priority: 1 },
      { videoId: "U0wbhLNSk-s", topic: "yann-lecun", priority: 1 },
      { videoId: "cFUUS5ZKY2s", topic: "joscha-bach", priority: 2 },
      { videoId: "hg44HjfEB6E", topic: "ray-kurzweil", priority: 1 },
      { videoId: "t06RUxP5_cU", topic: "roger-penrose", priority: 2 },
      { videoId: "59bMfm-Orns", topic: "vitalik-buterin", priority: 1 },
      { videoId: "KQ-9oAznq0w", topic: "john-carmack", priority: 1 },
      { videoId: "W87vgxZ-uXs", topic: "francois-chollet", priority: 1 },
      { videoId: "iZjby1IDH8k", topic: "yuval-harari", priority: 2 },
      { videoId: "NHnfuj7iDJc", topic: "george-hotz", priority: 2 },
      { videoId: "gPfpei_VShQ", topic: "ben-goertzel", priority: 2 },
      { videoId: "vfYmkj4rC3Q", topic: "michio-kaku", priority: 2 },
      { videoId: "iFjMf6zzD0Q", topic: "sam-harris", priority: 2 },
      { videoId: "MV5vvr8cfNw", topic: "pieter-abbeel", priority: 1 },
      { videoId: "Gfr50K6cVaY", topic: "andrew-bustamante", priority: 2 },
      { videoId: "ZPUtA3tN6PE", topic: "david-fravor", priority: 2 },
      { videoId: "tYKRiIfQsY0", topic: "eliezer-yudkowsky", priority: 1 },
      { videoId: "tYINh16Bev4", topic: "gpt4", priority: 1 },
      { videoId: "c3bRNN5RJ5U", topic: "ilya-sutskever", priority: 1 },
      { videoId: "9ENJfet1lHU", topic: "garry-tan", priority: 2 },
      { videoId: "dNrTrx42N8M", topic: "george-hotz", priority: 2 },
      { videoId: "WAYS-ZHTkzo", topic: "balaji-srinivasan", priority: 2 },
      { videoId: "NbOq8UiKJe0", topic: "ari-emanuel", priority: 2 },
      { videoId: "3t25w27BvdE", topic: "stephen-wolfram", priority: 1 },
      { videoId: "DxREm3s61ok", topic: "kimbal-musk", priority: 2 },
      { videoId: "8rXD5yxPHy4", topic: "jeff-hawkins", priority: 2 },
      { videoId: "UxcO-UsMVYo", topic: "sam-harris", priority: 2 },
      { videoId: "G42RJ4m0YyI", topic: "robert-playter", priority: 2 },
      { videoId: "QJ9-ZKhQ7uE", topic: "geoffrey-hinton", priority: 1 },
      { videoId: "IdYYjKkxsB8", topic: "sam-altman", priority: 2 },
      { videoId: "c_cNGegc5zU", topic: "elon-musk", priority: 2 },
      { videoId: "wT8SZV9ogbE", topic: "elon-musk", priority: 2 },
      { videoId: "GvYYFloRy0o", topic: "jeff-dean", priority: 1 },
      { videoId: "QJ0fUmZSShE", topic: "elon-musk", priority: 2 },
      { videoId: "YRfjvgnFQx4", topic: "science", priority: 2 },
      { videoId: "fuejOk0OZBE", topic: "consciousness", priority: 2 },
      { videoId: "rLqwlQZX0KU", topic: "mathematics", priority: 2 },
      { videoId: "2i2fFBi9N3w", topic: "biology", priority: 2 },
      { videoId: "nF_YWdz6X5s", topic: "psychology", priority: 2 },
      { videoId: "3t2n5UtbnGY", topic: "cosmology", priority: 2 },
      { videoId: "rCauH7TFxjI", topic: "history", priority: 3 },
      { videoId: "MoPdEDu9-xI", topic: "neuroscience", priority: 2 },
      { videoId: "r-fwlvBuyzw", topic: "engineering", priority: 2 },
      { videoId: "KOwm7CTFn6c", topic: "robotics", priority: 2 },
      { videoId: "9ztaSRB3p8o", topic: "music", priority: 3 },
      { videoId: "7kFeJcDusMs", topic: "energy", priority: 2 },
      { videoId: "CdZN93LkyXc", topic: "physics", priority: 2 },
      { videoId: "Qc2BnGwQzkg", topic: "demis-hassabis", priority: 1 },
      { videoId: "1aA1WGNSsMo", topic: "free-speech", priority: 3 },
      { videoId: "MvYL6EeoUaI", topic: "jack-dorsey", priority: 2 },
      { videoId: "9NOkEhTNEjY", topic: "space", priority: 2 },
      { videoId: "L_Guz73e6fw", topic: "openai", priority: 1 },
    ],
  },
  {
    slug: "dwarkesh-patel",
    name: "Dwarkesh Patel",
    category: "AI podcasts",
    videos: [
      { videoId: "is-O3mKdYFw", topic: "patrick-collison", priority: 1 },
      { videoId: "p8Jx4qvDoSo", topic: "sarah-paine", priority: 2 },
      { videoId: "tOtdJkpV2Vw", topic: "dario-amodei", priority: 1 },
      { videoId: "lXUZvyajciY", topic: "patrick-collison", priority: 2 },
      { videoId: "V979WdHSqO8", topic: "dario-amodei", priority: 1 },
      { videoId: "0jspaGHBaHA", topic: "sarah-paine", priority: 2 },
      { videoId: "x-ehJTxkQas", topic: "economics", priority: 2 },
      { videoId: "7gKJKHfqejA", topic: "ai-safety", priority: 2 },
      { videoId: "nis745H7YRc", topic: "scaling-laws", priority: 2 },
    ],
  },
  {
    slug: "andrej-karpathy",
    name: "Andrej Karpathy",
    category: "AI podcasts",
    videos: [
      { videoId: "kCc8FmEb1nY", topic: "large-language-models", priority: 1 },
      { videoId: "LWiM-LuRe6Q", topic: "neural-networks", priority: 1 },
      { videoId: "u1wT0mEurCU", topic: "gpt", priority: 1 },
    ],
  },
  {
    slug: "ai-explained",
    name: "AI Explained",
    category: "AI podcasts",
    videos: [
      { videoId: "h1AzMaWYkmg", topic: "ai-news", priority: 2 },
    ],
  },
  {
    slug: "openai",
    name: "OpenAI",
    category: "AI podcasts",
    videos: [
      { videoId: "wbEk6mIlDMc", topic: "devday", priority: 1 },
    ],
  },
  {
    slug: "stanford",
    name: "Stanford",
    category: "AI podcasts",
    videos: [
      { videoId: "p0FERNkpyHE", topic: "sam-altman", priority: 1 },
    ],
  },
  {
    slug: "hard-fork",
    name: "Hard Fork",
    category: "AI podcasts",
    videos: [
      { videoId: "5MWT_doo68k", topic: "tech-news", priority: 2 },
    ],
  },
  {
    slug: "no-priors",
    name: "No Priors",
    category: "AI podcasts",
    videos: [
      { videoId: "HAn9sNAJLHQ", topic: "venture-ai", priority: 2 },
    ],
  },
  {
    slug: "a16z",
    name: "a16z",
    category: "AI podcasts",
    videos: [
      { videoId: "6_1QLHugH3c", topic: "ai-startups", priority: 2 },
    ],
  },
  {
    slug: "y-combinator",
    name: "Y Combinator",
    category: "AI podcasts",
    videos: [
      { videoId: "Z1Lufu0FSrI", topic: "ai-startup-school", priority: 2 },
    ],
  },
  {
    slug: "y-combinator",
    name: "Y Combinator",
    category: "business interviews",
    videos: [
      { videoId: "CBYhVc0glP8", topic: "startup-advice", priority: 1 },
      { videoId: "CnE3V9ZPyhk", topic: "founder-stories", priority: 1 },
      { videoId: "GYl6WpV3FoU", topic: "saas", priority: 1 },
      { videoId: "T9ikpoF2GH0", topic: "fundraising", priority: 1 },
      { videoId: "V993GZwcS-c", topic: "product-market-fit", priority: 1 },
      { videoId: "St5fVtlDI_Q", topic: "b2b-sales", priority: 2 },
      { videoId: "6WtdFqgsEY0", topic: "hiring", priority: 2 },
      { videoId: "XsZSxXU4-qQ", topic: "pivoting", priority: 2 },
      { videoId: "hF515-0TQk4", topic: "startup-playbook", priority: 1 },
      { videoId: "4aQAgAjTozk", topic: "founder-mode", priority: 1 },
      { videoId: "IACHfKm9Mow", topic: "yc-interview", priority: 2 },
      { videoId: "MT4Ig2uqjTc", topic: "customer-discovery", priority: 1 },
      { videoId: "Th8JoIan4dg", topic: "startup-ideas", priority: 2 },
    ],
  },
  {
    slug: "diary-of-a-ceo",
    name: "Diary of a CEO",
    category: "business interviews",
    videos: [
      { videoId: "zQctEb0JyYc", topic: "entrepreneurship", priority: 1 },
      { videoId: "NbDgg22f0B0", topic: "leadership", priority: 1 },
      { videoId: "b67LiRvIDBc", topic: "founder-mindset", priority: 1 },
    ],
  },
  {
    slug: "my-first-million",
    name: "My First Million",
    category: "business interviews",
    videos: [
      { videoId: "F9LWUVJeGxw", topic: "startup-ideas", priority: 2 },
      { videoId: "oWZbWzAyHAE", topic: "business-growth", priority: 2 },
    ],
  },
  {
    slug: "gary-vaynerchuk",
    name: "Gary Vaynerchuk",
    category: "business interviews",
    videos: [
      { videoId: "d0yGdNEWdn0", topic: "marketing", priority: 2 },
    ],
  },
  {
    slug: "harvard-i-lab",
    name: "Harvard i-lab",
    category: "business interviews",
    videos: [
      { videoId: "G3e-cpL7ofc", topic: "entrepreneurship", priority: 2 },
    ],
  },
  {
    slug: "stanford",
    name: "Stanford",
    category: "business interviews",
    videos: [
      { videoId: "UF8uR6Z6KLc", topic: "steve-jobs", priority: 1 },
    ],
  },
  {
    slug: "stanford-ecorner",
    name: "Stanford eCorner",
    category: "business interviews",
    videos: [
      { videoId: "7bB__8O9Y8c", topic: "startup-lessons", priority: 2 },
    ],
  },
  {
    slug: "the-plain-bagel",
    name: "The Plain Bagel",
    category: "finance education",
    videos: [
      { videoId: "8VGHIH5FBA8", topic: "investing-basics", priority: 1 },
      { videoId: "TJDcN3pm4us", topic: "stock-market", priority: 1 },
      { videoId: "IjnRJXPct1k", topic: "index-funds", priority: 1 },
      { videoId: "wX8fWXefGLc", topic: "passive-investing", priority: 2 },
    ],
  },
  {
    slug: "graham-stephan",
    name: "Graham Stephan",
    category: "finance education",
    videos: [
      { videoId: "lNdOtlpmH5U", topic: "personal-finance", priority: 1 },
      { videoId: "9R_SaLH1lOc", topic: "real-estate", priority: 2 },
      { videoId: "hJnw3TQXNDs", topic: "housing-market", priority: 2 },
    ],
  },
  {
    slug: "whiteboard-finance",
    name: "Whiteboard Finance",
    category: "finance education",
    videos: [
      { videoId: "UZBKE1b2tMI", topic: "investing", priority: 1 },
    ],
  },
  {
    slug: "khan-academy",
    name: "Khan Academy",
    category: "finance education",
    videos: [
      { videoId: "gw6Llagaa4o", topic: "finance-intro", priority: 1 },
      { videoId: "rD6L2FmvduI", topic: "compound-interest", priority: 1 },
      { videoId: "WEDIj9JBTCk", topic: "personal-finance", priority: 2 },
    ],
  },
  {
    slug: "ray-dalio",
    name: "Ray Dalio",
    category: "finance education",
    videos: [
      { videoId: "wjc7FzeD7gg", topic: "economic-principles", priority: 1 },
      { videoId: "6Zr0v5q2e7U", topic: "debt-cycles", priority: 2 },
      { videoId: "B9XG_upIDOE", topic: "economic-cycles", priority: 1 },
    ],
  },
  {
    slug: "warren-buffett",
    name: "Warren Buffett",
    category: "finance education",
    videos: [
      { videoId: "TMF1I-9NVOw", topic: "investing-wisdom", priority: 1 },
      { videoId: "2MhiHBFMoUk", topic: "value-investing", priority: 1 },
    ],
  },
  {
    slug: "andrew-huberman",
    name: "Andrew Huberman",
    category: "self-improvement podcasts",
    videos: [
      { videoId: "4HiueBzp2w8", topic: "dopamine", priority: 1 },
      { videoId: "w42a_LeP4FY", topic: "motivation", priority: 1 },
      { videoId: "K1ng2KVDlzE", topic: "caffeine", priority: 2 },
      { videoId: "1gmpCIuo-vA", topic: "fitness", priority: 1 },
      { videoId: "ozHwx-jsF-w", topic: "cold-exposure", priority: 2 },
      { videoId: "7CKVpHv5Y-k", topic: "stress", priority: 1 },
      { videoId: "UZMUPw8pP0o", topic: "meditation", priority: 2 },
      { videoId: "y3Umo_jd5AA", topic: "learning", priority: 2 },
      { videoId: "hFL6qRIJZ_Y", topic: "focus", priority: 1 },
      { videoId: "nm1TxQj9IsQ", topic: "sleep", priority: 1 },
    ],
  },
  {
    slug: "tim-ferriss",
    name: "Tim Ferriss",
    category: "self-improvement podcasts",
    videos: [
      { videoId: "eB2LUXaSOfU", topic: "performance", priority: 1 },
      { videoId: "QmOF0crdyRU", topic: "productivity", priority: 2 },
    ],
  },
  {
    slug: "naval-ravikant",
    name: "Naval Ravikant",
    category: "self-improvement podcasts",
    videos: [
      { videoId: "TAKErg_Duk4", topic: "happiness", priority: 1 },
    ],
  },
  {
    slug: "jay-shetty",
    name: "Jay Shetty",
    category: "self-improvement podcasts",
    videos: [
      { videoId: "3qHkc9OOzcQ", topic: "habits", priority: 2 },
    ],
  },
  {
    slug: "jocko-willink",
    name: "Jocko Willink",
    category: "self-improvement podcasts",
    videos: [
      { videoId: "6ZrlsVx85ek", topic: "discipline", priority: 1 },
    ],
  },
  {
    slug: "cal-newport",
    name: "Cal Newport",
    category: "self-improvement podcasts",
    videos: [
      { videoId: "ktiZ5j4QO0A", topic: "deep-work", priority: 1 },
    ],
  },
  {
    slug: "james-clear",
    name: "James Clear",
    category: "self-improvement podcasts",
    videos: [
      { videoId: "l7FSOuFnWRo", topic: "atomic-habits", priority: 1 },
    ],
  },
  {
    slug: "corey-schafer",
    name: "Corey Schafer",
    category: "programming tutorials",
    videos: [
      { videoId: "HGOBQPFzWKo", topic: "terminal", priority: 2 },
      { videoId: "eWRfhZUzrAc", topic: "python", priority: 2 },
      { videoId: "7wnove7K-ZQ", topic: "python", priority: 2 },
      { videoId: "fKl2JW_qrso", topic: "django", priority: 1 },
      { videoId: "UmljXZIypDc", topic: "django", priority: 2 },
      { videoId: "HGoYwMBk6a8", topic: "python-oop", priority: 1 },
      { videoId: "DZtn3fDLMTA", topic: "python-decorators", priority: 2 },
      { videoId: "Da-2h2B4fbU", topic: "flask", priority: 1 },
      { videoId: "jBzwzrDvZbc", topic: "python", priority: 2 },
      { videoId: "N5vscRTVt7M", topic: "django", priority: 2 },
      { videoId: "c4M26jsVr70", topic: "django", priority: 2 },
    ],
  },
  {
    slug: "3blue1brown",
    name: "3Blue1Brown",
    category: "programming tutorials",
    videos: [
      { videoId: "aircAruvnKk", topic: "neural-networks", priority: 1 },
      { videoId: "IHZwWFHWa-w", topic: "linear-algebra", priority: 1 },
      { videoId: "jGw_UM8cfgA", topic: "neural-networks", priority: 1 },
    ],
  },
  {
    slug: "stanford-online",
    name: "Stanford Online",
    category: "AI podcasts",
    videos: [
      { videoId: "PaCmpygFfXo", topic: "computer-vision", priority: 1 },
      { videoId: "PySo_6S4ZAg", topic: "transformers", priority: 1 },
      { videoId: "4PaBNEd6SR4", topic: "nlp", priority: 1 },
      { videoId: "vT1Zj5rWpYM", topic: "cs224n", priority: 1 },
      { videoId: "MNIwwo_nZpY", topic: "deep-learning", priority: 1 },
    ],
  },
  {
    slug: "deeplearning.ai",
    name: "DeepLearning.AI",
    category: "AI podcasts",
    videos: [
      { videoId: "7xTGNNLPyMI", topic: "deep-learning", priority: 1 },
      { videoId: "4b4MUYve_U8", topic: "machine-learning", priority: 2 },
    ],
  },
  {
    slug: "yannic-kilcher",
    name: "Yannic Kilcher",
    category: "AI podcasts",
    videos: [
      { videoId: "CDiqA4SJNpA", topic: "machine-learning", priority: 2 },
    ],
  },
  {
    slug: "the-net-ninja",
    name: "The Net Ninja",
    category: "programming tutorials",
    videos: [
      { videoId: "ItZ2TmIj40U", topic: "javascript", priority: 1 },
      { videoId: "iLBT0lOdLFQ", topic: "vue", priority: 1 },
      { videoId: "YrxBCB_bVgM", topic: "nuxt", priority: 2 },
      { videoId: "bi5vhY9CLfw", topic: "vuex", priority: 2 },
      { videoId: "3aS1KRz_Z9k", topic: "tailwind", priority: 1 },
    ],
  },
  {
    slug: "stanford-online",
    name: "Stanford Online",
    category: "programming tutorials",
    videos: [
      { videoId: "6xTHwMtNq_Y", topic: "machine-learning", priority: 1 },
    ],
  },
  {
    slug: "fireship",
    name: "Fireship",
    category: "programming tutorials",
    videos: [
      { videoId: "Tn6-PIqc4UM", topic: "react", priority: 2 },
    ],
  },
  {
    slug: "mit-opencourseware",
    name: "MIT OpenCourseWare",
    category: "finance education",
    videos: [
      { videoId: "ZK3O402wf1c", topic: "linear-algebra", priority: 3 },
    ],
  },
];

export const SEED_CHANNEL_CATEGORIES = [...new Set(SEED_CHANNEL_CATALOG.map((channel) => channel.category))];