import type { TopicSeed } from "@/lib/topic-keywords";
import { GENERATED_TOPIC_SEEDS } from "@/lib/generated-topic-seeds";

const MANUAL_TOPIC_SEEDS: TopicSeed[] = [
  { slug: "youtube-transcripts", displayName: "YouTube transcripts", cluster: "youtube-transcript-search", description: "Search full YouTube video transcripts and jump to exact mentions instantly.", featured: false },
  { slug: "transcript-search", displayName: "Transcript search", cluster: "youtube-transcript-search", description: "Search any YouTube transcript for keywords, phrases, and speaker moments.", featured: true },
  { slug: "find-youtube-quotes", displayName: "Find YouTube quotes", cluster: "youtube-transcript-search", description: "Locate quotable lines inside YouTube videos without manual scrubbing.", featured: true },
  { slug: "youtube-captions", displayName: "YouTube captions", cluster: "youtube-transcript-search", description: "Search YouTube captions and open the timestamp where a phrase appears.", featured: false },
  { slug: "youtube-timestamps", displayName: "YouTube timestamps", cluster: "youtube-transcript-search", description: "Find exact YouTube timestamps from transcript matches in seconds.", featured: false },
  { slug: "search-captions", displayName: "Search captions", cluster: "youtube-transcript-search", description: "Search video captions across podcasts, lectures, and tutorials on YouTube.", featured: false },
  { slug: "video-transcript", displayName: "Video transcript", cluster: "youtube-transcript-search", description: "Read and search a YouTube video transcript to find the right moment fast.", featured: false },
  { slug: "caption-search", displayName: "Caption search", cluster: "youtube-transcript-search", description: "Run caption search on long YouTube videos and jump to matching lines.", featured: false },
  { slug: "timestamp-finder", displayName: "Timestamp finder", cluster: "youtube-transcript-search", description: "Use transcript search as a timestamp finder for interviews and lectures.", featured: false },
  { slug: "quote-finder", displayName: "Quote finder", cluster: "youtube-transcript-search", description: "Find shareable quotes inside YouTube transcripts with direct timestamp links.", featured: false },
  { slug: "podcast-transcript", displayName: "Podcast transcript", cluster: "youtube-transcript-search", description: "Search podcast transcripts uploaded to YouTube and skip to key segments.", featured: true },
  { slug: "interview-transcript", displayName: "Interview transcript", cluster: "youtube-transcript-search", description: "Search interview transcripts for names, topics, and memorable quotes.", featured: false },
  { slug: "lecture-transcript", displayName: "Lecture transcript", cluster: "youtube-transcript-search", description: "Find concepts and explanations inside lecture transcripts on YouTube.", featured: false },
  { slug: "tutorial-transcript", displayName: "Tutorial transcript", cluster: "youtube-transcript-search", description: "Search tutorial transcripts for steps, commands, and troubleshooting tips.", featured: false },
  { slug: "webinar-transcript", displayName: "Webinar transcript", cluster: "youtube-transcript-search", description: "Jump to answers and demos inside webinar transcripts on YouTube.", featured: false },
  { slug: "keynote-transcript", displayName: "Keynote transcript", cluster: "youtube-transcript-search", description: "Search keynote transcripts for product launches, vision, and strategy lines.", featured: false },
  { slug: "conference-talk", displayName: "Conference talk", cluster: "youtube-transcript-search", description: "Find ideas inside conference talk transcripts without watching full sessions.", featured: false },
  { slug: "ted-talk", displayName: "TED talk", cluster: "youtube-transcript-search", description: "Search TED talk transcripts for memorable lines and core arguments.", featured: false },
  { slug: "documentary-transcript", displayName: "Documentary transcript", cluster: "youtube-transcript-search", description: "Locate facts and narration moments inside documentary transcripts.", featured: false },
  { slug: "audiobook-clips", displayName: "Audiobook clips", cluster: "youtube-transcript-search", description: "Find audiobook-style clips and readings shared on YouTube.", featured: false },
  { slug: "podcasts", displayName: "Podcasts", cluster: "podcasts", description: "Search podcast episodes on YouTube by transcript keyword or guest topic.", featured: false },
  { slug: "podcast-clips", displayName: "Podcast clips", cluster: "podcasts", description: "Find the best podcast clips by searching transcript moments on YouTube.", featured: true },
  { slug: "podcast-quotes", displayName: "Podcast quotes", cluster: "podcasts", description: "Locate quotable podcast lines and share timestamped clip pages.", featured: false },
  { slug: "podcast-highlights", displayName: "Podcast highlights", cluster: "podcasts", description: "Discover highlight-worthy podcast segments through transcript search.", featured: false },
  { slug: "podcast-moments", displayName: "Podcast moments", cluster: "podcasts", description: "Jump to standout podcast moments in long-form YouTube uploads.", featured: false },
  { slug: "podcast-interviews", displayName: "Podcast interviews", cluster: "podcasts", description: "Search podcast interview transcripts for guest insights and stories.", featured: true },
  { slug: "long-form-podcast", displayName: "Long-form podcast", cluster: "podcasts", description: "Search multi-hour podcast transcripts without endless scrubbing.", featured: false },
  { slug: "true-crime-podcast", displayName: "True crime podcast", cluster: "podcasts", description: "Find case details and timeline moments in true crime podcast transcripts.", featured: false },
  { slug: "comedy-podcast", displayName: "Comedy podcast", cluster: "podcasts", description: "Search comedy podcast transcripts for bits, jokes, and memorable riffs.", featured: false },
  { slug: "tech-podcast", displayName: "Tech podcast", cluster: "podcasts", description: "Locate product, startup, and engineering discussions in tech podcasts.", featured: false },
  { slug: "business-podcast", displayName: "Business podcast", cluster: "podcasts", description: "Search business podcast transcripts for strategy, growth, and leadership advice.", featured: false },
  { slug: "health-podcast", displayName: "Health podcast", cluster: "podcasts", description: "Find health and wellness discussions inside podcast transcripts on YouTube.", featured: false },
  { slug: "science-podcast", displayName: "Science podcast", cluster: "podcasts", description: "Search science podcast transcripts for studies, explanations, and debates.", featured: false },
  { slug: "politics-podcast", displayName: "Politics podcast", cluster: "podcasts", description: "Find policy arguments and political commentary inside podcast transcripts.", featured: false },
  { slug: "history-podcast", displayName: "History podcast", cluster: "podcasts", description: "Search history podcast transcripts for events, figures, and narratives.", featured: false },
  { slug: "storytelling-podcast", displayName: "Storytelling podcast", cluster: "podcasts", description: "Locate compelling stories inside storytelling podcast transcripts.", featured: false },
  { slug: "narrative-podcast", displayName: "Narrative podcast", cluster: "podcasts", description: "Search narrative podcast transcripts for plot points and character arcs.", featured: false },
  { slug: "audio-clips", displayName: "Audio clips", cluster: "podcasts", description: "Find short audio clips and spoken moments inside YouTube transcripts.", featured: false },
  { slug: "episode-highlights", displayName: "Episode highlights", cluster: "podcasts", description: "Jump to episode highlights by searching transcript keywords.", featured: false },
  { slug: "clip-search", displayName: "Clip search", cluster: "podcasts", description: "Use clip search on YouTube transcripts to build shareable timestamp links.", featured: false },
  { slug: "startup", displayName: "Startup", cluster: "creator-business", description: "Search startup advice, founder stories, and pitch moments in YouTube transcripts.", featured: true },
  { slug: "saas", displayName: "SaaS", cluster: "creator-business", description: "Find SaaS growth, pricing, and product lessons inside interview transcripts.", featured: false },
  { slug: "business", displayName: "Business", cluster: "creator-business", description: "Search business strategy clips, case studies, and operator advice on YouTube.", featured: false },
  { slug: "marketing", displayName: "Marketing", cluster: "creator-business", description: "Locate marketing frameworks, campaigns, and growth tactics in video transcripts.", featured: true },
  { slug: "sales", displayName: "Sales", cluster: "creator-business", description: "Find sales objections, closing techniques, and pipeline advice in transcripts.", featured: false },
  { slug: "copywriting", displayName: "Copywriting", cluster: "creator-business", description: "Search copywriting tips, hooks, and examples inside creator transcripts.", featured: false },
  { slug: "entrepreneurship", displayName: "Entrepreneurship", cluster: "creator-business", description: "Jump to entrepreneurship lessons in interviews, panels, and lectures.", featured: true },
  { slug: "branding", displayName: "Branding", cluster: "creator-business", description: "Search branding discussions for positioning, voice, and audience building.", featured: false },
  { slug: "content-creation", displayName: "Content creation", cluster: "creator-business", description: "Find content creation workflows and platform strategy in YouTube videos.", featured: false },
  { slug: "youtube-growth", displayName: "YouTube growth", cluster: "creator-business", description: "Search YouTube growth advice about thumbnails, retention, and audience strategy.", featured: false },
  { slug: "audience-building", displayName: "Audience building", cluster: "creator-business", description: "Locate audience-building tactics inside creator and marketer transcripts.", featured: false },
  { slug: "monetization", displayName: "Monetization", cluster: "creator-business", description: "Find monetization models, sponsorships, and revenue advice in transcripts.", featured: false },
  { slug: "creator-economy", displayName: "Creator economy", cluster: "creator-business", description: "Search creator economy trends, tools, and business model discussions.", featured: false },
  { slug: "influencer-marketing", displayName: "Influencer marketing", cluster: "creator-business", description: "Find influencer marketing playbooks and campaign breakdowns on YouTube.", featured: false },
  { slug: "email-marketing", displayName: "Email marketing", cluster: "creator-business", description: "Search email marketing funnels, copy, and list-building advice in videos.", featured: false },
  { slug: "social-media-strategy", displayName: "Social media strategy", cluster: "creator-business", description: "Locate social media strategy clips across interviews and tutorials.", featured: false },
  { slug: "personal-brand", displayName: "Personal brand", cluster: "creator-business", description: "Find personal brand advice about positioning, content, and credibility.", featured: false },
  { slug: "freelancing", displayName: "Freelancing", cluster: "creator-business", description: "Search freelancing tips on pricing, clients, and portfolio building.", featured: false },
  { slug: "consulting", displayName: "Consulting", cluster: "creator-business", description: "Find consulting frameworks and client acquisition advice in transcripts.", featured: false },
  { slug: "agency-growth", displayName: "Agency growth", cluster: "creator-business", description: "Search agency growth content about hiring, delivery, and retainers.", featured: false },
  { slug: "product-launch", displayName: "Product launch", cluster: "creator-business", description: "Locate product launch strategy and go-live lessons in startup transcripts.", featured: false },
  { slug: "go-to-market", displayName: "Go-to-market", cluster: "creator-business", description: "Find go-to-market plans, ICP definitions, and channel strategy moments.", featured: false },
  { slug: "pricing-strategy", displayName: "Pricing strategy", cluster: "creator-business", description: "Search pricing strategy discussions in SaaS and business interviews.", featured: false },
  { slug: "customer-acquisition", displayName: "Customer acquisition", cluster: "creator-business", description: "Find customer acquisition tactics in growth and marketing transcripts.", featured: false },
  { slug: "retention", displayName: "Retention", cluster: "creator-business", description: "Search retention, churn, and lifecycle advice inside product interviews.", featured: false },
  { slug: "productivity", displayName: "Productivity", cluster: "productivity", description: "Search productivity systems, routines, and focus advice in YouTube transcripts.", featured: true },
  { slug: "habits", displayName: "Habits", cluster: "productivity", description: "Find habit-building frameworks and behavior change advice in video transcripts.", featured: true },
  { slug: "focus", displayName: "Focus", cluster: "productivity", description: "Locate focus techniques and distraction-management tips in lectures and podcasts.", featured: true },
  { slug: "discipline", displayName: "Discipline", cluster: "productivity", description: "Search discipline advice for consistency, execution, and self-control.", featured: false },
  { slug: "motivation", displayName: "Motivation", cluster: "productivity", description: "Find motivation talks and practical mindset shifts inside long videos.", featured: false },
  { slug: "procrastination", displayName: "Procrastination", cluster: "productivity", description: "Search procrastination explanations and anti-procrastination tactics.", featured: false },
  { slug: "deep-work", displayName: "Deep work", cluster: "productivity", description: "Locate deep work strategies for concentration and high-quality output.", featured: true },
  { slug: "time-management", displayName: "Time management", cluster: "productivity", description: "Find time management systems in productivity podcasts and lectures.", featured: false },
  { slug: "goal-setting", displayName: "Goal setting", cluster: "productivity", description: "Search goal-setting frameworks and planning advice in transcripts.", featured: false },
  { slug: "morning-routine", displayName: "Morning routine", cluster: "productivity", description: "Find morning routine ideas and habit stacks in creator transcripts.", featured: false },
  { slug: "note-taking", displayName: "Note taking", cluster: "productivity", description: "Search note-taking methods like Zettelkasten and active recall in lectures.", featured: false },
  { slug: "second-brain", displayName: "Second brain", cluster: "productivity", description: "Locate second-brain and PKM workflows in productivity content.", featured: false },
  { slug: "workflow", displayName: "Workflow", cluster: "productivity", description: "Find workflow optimization tips for knowledge work and creative output.", featured: false },
  { slug: "automation", displayName: "Automation", cluster: "productivity", description: "Search automation advice for tasks, tools, and personal systems.", featured: false },
  { slug: "prioritization", displayName: "Prioritization", cluster: "productivity", description: "Find prioritization frameworks like Eisenhower and OKRs in transcripts.", featured: false },
  { slug: "energy-management", displayName: "Energy management", cluster: "productivity", description: "Search energy management advice for sleep, movement, and recovery.", featured: false },
  { slug: "burnout", displayName: "Burnout", cluster: "productivity", description: "Locate burnout prevention and recovery discussions in wellness content.", featured: false },
  { slug: "work-life-balance", displayName: "Work-life balance", cluster: "productivity", description: "Find work-life balance advice in interviews and coaching transcripts.", featured: false },
  { slug: "remote-work", displayName: "Remote work", cluster: "productivity", description: "Search remote work productivity, communication, and async tips.", featured: false },
  { slug: "calendar-management", displayName: "Calendar management", cluster: "productivity", description: "Find calendar management tactics for deep work and meeting load.", featured: false },
  { slug: "fitness", displayName: "Fitness", cluster: "health-fitness", description: "Search fitness training advice, programs, and form cues in YouTube transcripts.", featured: true },
  { slug: "nutrition", displayName: "Nutrition", cluster: "health-fitness", description: "Find nutrition guidance, meal planning, and diet debates in health videos.", featured: true },
  { slug: "sleep", displayName: "Sleep", cluster: "health-fitness", description: "Locate sleep science, routines, and recovery advice in podcast transcripts.", featured: true },
  { slug: "health", displayName: "Health", cluster: "health-fitness", description: "Search general health discussions across podcasts, lectures, and clinics.", featured: false },
  { slug: "weight-loss", displayName: "Weight loss", cluster: "health-fitness", description: "Find weight loss strategies and evidence-based advice in transcripts.", featured: false },
  { slug: "strength-training", displayName: "Strength training", cluster: "health-fitness", description: "Search strength training programming and technique explanations.", featured: false },
  { slug: "cardio", displayName: "Cardio", cluster: "health-fitness", description: "Locate cardio training guidance and endurance science in fitness videos.", featured: false },
  { slug: "longevity", displayName: "Longevity", cluster: "health-fitness", description: "Find longevity research discussions and lifestyle protocols in transcripts.", featured: false },
  { slug: "biohacking", displayName: "Biohacking", cluster: "health-fitness", description: "Search biohacking experiments, tools, and self-tracking advice.", featured: false },
  { slug: "supplements", displayName: "Supplements", cluster: "health-fitness", description: "Find supplement discussions with dosing context in health podcasts.", featured: false },
  { slug: "fasting", displayName: "Fasting", cluster: "health-fitness", description: "Search fasting protocols and metabolic explanations in lecture transcripts.", featured: false },
  { slug: "meditation", displayName: "Meditation", cluster: "health-fitness", description: "Locate meditation instructions and mindfulness research in videos.", featured: false },
  { slug: "yoga", displayName: "Yoga", cluster: "health-fitness", description: "Find yoga practice guidance and philosophy moments in class transcripts.", featured: false },
  { slug: "mental-wellness", displayName: "Mental wellness", cluster: "health-fitness", description: "Search mental wellness topics across therapy and coaching content.", featured: false },
  { slug: "recovery", displayName: "Recovery", cluster: "health-fitness", description: "Find recovery protocols for training, sleep, and stress in health videos.", featured: false },
  { slug: "injury-prevention", displayName: "Injury prevention", cluster: "health-fitness", description: "Search injury prevention advice for mobility, load, and form.", featured: false },
  { slug: "diet", displayName: "Diet", cluster: "health-fitness", description: "Locate diet comparisons and nutrition science in evidence-based lectures.", featured: false },
  { slug: "gut-health", displayName: "Gut health", cluster: "health-fitness", description: "Find gut health and microbiome discussions in health podcasts.", featured: false },
  { slug: "hormones", displayName: "Hormones", cluster: "health-fitness", description: "Search hormone optimization and endocrine health topics in transcripts.", featured: false },
  { slug: "exercise-science", displayName: "Exercise science", cluster: "health-fitness", description: "Find exercise science explanations in academic and coach lectures.", featured: false },
  { slug: "psychology", displayName: "Psychology", cluster: "psychology", description: "Search psychology concepts, studies, and explanations in lecture transcripts.", featured: false },
  { slug: "dopamine", displayName: "Dopamine", cluster: "psychology", description: "Find dopamine discussions about motivation, reward, and habit loops.", featured: true },
  { slug: "anxiety", displayName: "Anxiety", cluster: "psychology", description: "Locate anxiety coping strategies and clinical explanations in videos.", featured: true },
  { slug: "adhd", displayName: "ADHD", cluster: "psychology", description: "Search ADHD productivity, diagnosis, and management advice in transcripts.", featured: true },
  { slug: "mindset", displayName: "Mindset", cluster: "psychology", description: "Find growth mindset and performance psychology moments in interviews.", featured: false },
  { slug: "emotional-intelligence", displayName: "Emotional intelligence", cluster: "psychology", description: "Search emotional intelligence skills in leadership and coaching content.", featured: false },
  { slug: "habits-psychology", displayName: "Habits psychology", cluster: "psychology", description: "Locate behavioral psychology behind habit formation and change.", featured: false },
  { slug: "cognitive-bias", displayName: "Cognitive bias", cluster: "psychology", description: "Find cognitive bias examples and debiasing strategies in lectures.", featured: false },
  { slug: "neuroscience", displayName: "Neuroscience", cluster: "psychology", description: "Search neuroscience explanations in Huberman-style and academic videos.", featured: false },
  { slug: "trauma", displayName: "Trauma", cluster: "psychology", description: "Locate trauma-informed discussions in therapy and psychology podcasts.", featured: false },
  { slug: "therapy", displayName: "Therapy", cluster: "psychology", description: "Find therapy modalities and mental health education in expert transcripts.", featured: false },
  { slug: "self-improvement", displayName: "Self improvement", cluster: "psychology", description: "Search self-improvement frameworks across podcasts and talks.", featured: false },
  { slug: "confidence", displayName: "Confidence", cluster: "psychology", description: "Find confidence-building advice in coaching and interview transcripts.", featured: false },
  { slug: "resilience", displayName: "Resilience", cluster: "psychology", description: "Search resilience training and adversity responses in psychology content.", featured: false },
  { slug: "stress-management", displayName: "Stress management", cluster: "psychology", description: "Locate stress management techniques in wellness lectures.", featured: false },
  { slug: "happiness", displayName: "Happiness", cluster: "psychology", description: "Find happiness research and practical well-being advice in transcripts.", featured: false },
  { slug: "relationships", displayName: "Relationships", cluster: "psychology", description: "Search relationship communication and attachment discussions.", featured: false },
  { slug: "attachment", displayName: "Attachment", cluster: "psychology", description: "Locate attachment theory explanations in psychology lectures.", featured: false },
  { slug: "communication-skills", displayName: "Communication skills", cluster: "psychology", description: "Find communication skills training in coaching and business videos.", featured: false },
  { slug: "persuasion", displayName: "Persuasion", cluster: "psychology", description: "Search persuasion psychology and influence tactics in marketing content.", featured: false },
  { slug: "ai", displayName: "AI", cluster: "ai-software", description: "Search AI breakthroughs, demos, and debates inside YouTube transcripts.", featured: true },
  { slug: "artificial-intelligence", displayName: "Artificial intelligence", cluster: "ai-software", description: "Search artificial intelligence lectures, demos, and debates across indexed long-form videos.", featured: true },
  { slug: "chatgpt", displayName: "ChatGPT", cluster: "ai-software", description: "Find ChatGPT tutorials, prompts, and workflow tips in tech videos.", featured: true },
  { slug: "machine-learning", displayName: "Machine learning", cluster: "ai-software", description: "Search machine learning lectures for models, training, and evaluation.", featured: false },
  { slug: "coding", displayName: "Coding", cluster: "ai-software", description: "Find coding tutorials, walkthroughs, and debugging explanations on YouTube.", featured: true },
  { slug: "javascript", displayName: "JavaScript", cluster: "ai-software", description: "Search JavaScript tutorials for syntax, frameworks, and project builds.", featured: false },
  { slug: "python", displayName: "Python", cluster: "ai-software", description: "Locate Python lessons for scripting, data, and backend development.", featured: false },
  { slug: "react", displayName: "React", cluster: "ai-software", description: "Find React component patterns, hooks, and app tutorials in transcripts.", featured: false },
  { slug: "typescript", displayName: "TypeScript", cluster: "ai-software", description: "Search TypeScript typing patterns and migration advice in dev videos.", featured: false },
  { slug: "software-engineering", displayName: "Software engineering", cluster: "ai-software", description: "Find software engineering practices in conference and course transcripts.", featured: false },
  { slug: "web-development", displayName: "Web development", cluster: "ai-software", description: "Search web development tutorials for frontend and backend topics.", featured: false },
  { slug: "mobile-development", displayName: "Mobile development", cluster: "ai-software", description: "Locate mobile development lessons for iOS, Android, and Flutter.", featured: false },
  { slug: "devops", displayName: "DevOps", cluster: "ai-software", description: "Find DevOps pipeline, CI/CD, and infrastructure advice in tech talks.", featured: false },
  { slug: "cloud-computing", displayName: "Cloud computing", cluster: "ai-software", description: "Search cloud computing architecture lessons on AWS, GCP, and Azure.", featured: false },
  { slug: "cybersecurity", displayName: "Cybersecurity", cluster: "ai-software", description: "Locate cybersecurity explanations for threats, hardening, and incident response.", featured: false },
  { slug: "data-science", displayName: "Data science", cluster: "ai-software", description: "Find data science workflows, notebooks, and modeling talks on YouTube.", featured: false },
  { slug: "llm", displayName: "LLM", cluster: "ai-software", description: "Search large language model discussions about training, RAG, and agents.", featured: false },
  { slug: "prompt-engineering", displayName: "Prompt engineering", cluster: "ai-software", description: "Find prompt engineering techniques in AI tool tutorials.", featured: false },
  { slug: "automation-tools", displayName: "Automation tools", cluster: "ai-software", description: "Search automation tool walkthroughs for no-code and scripting workflows.", featured: false },
  { slug: "no-code", displayName: "No-code", cluster: "ai-software", description: "Locate no-code build tutorials and product launch stories in transcripts.", featured: false },
  { slug: "api-development", displayName: "API development", cluster: "ai-software", description: "Find API development patterns, auth, and versioning in engineering videos.", featured: false },
  { slug: "open-source", displayName: "Open source", cluster: "ai-software", description: "Search open-source project talks about community, licensing, and maintenance.", featured: false },
  { slug: "github", displayName: "GitHub", cluster: "ai-software", description: "Find GitHub workflow tips for PRs, actions, and collaboration in dev content.", featured: false },
  { slug: "debugging", displayName: "Debugging", cluster: "ai-software", description: "Search debugging walkthroughs and error-resolution explanations.", featured: false },
  { slug: "system-design", displayName: "System design", cluster: "ai-software", description: "Locate system design interview explanations and architecture breakdowns.", featured: false },
  { slug: "full-stack", displayName: "Full stack", cluster: "ai-software", description: "Find full-stack project tutorials spanning frontend, backend, and deployment.", featured: false },
  { slug: "money", displayName: "Money", cluster: "money-investing", description: "Search money mindset, income, and wealth-building advice in YouTube transcripts.", featured: true },
  { slug: "investing", displayName: "Investing", cluster: "money-investing", description: "Find investing frameworks, portfolio theory, and market commentary.", featured: true },
  { slug: "bitcoin", displayName: "Bitcoin", cluster: "money-investing", description: "Search Bitcoin explanations, debates, and macro discussions in podcasts.", featured: true },
  { slug: "crypto", displayName: "Crypto", cluster: "money-investing", description: "Locate crypto project reviews, tokenomics, and risk discussions.", featured: false },
  { slug: "stocks", displayName: "Stocks", cluster: "money-investing", description: "Find stock analysis, earnings breakdowns, and valuation lessons in videos.", featured: false },
  { slug: "real-estate", displayName: "Real estate", cluster: "money-investing", description: "Search real estate investing strategies and market updates in transcripts.", featured: false },
  { slug: "personal-finance", displayName: "Personal finance", cluster: "money-investing", description: "Find personal finance basics on budgeting, debt, and savings.", featured: false },
  { slug: "wealth-building", displayName: "Wealth building", cluster: "money-investing", description: "Search wealth-building playbooks in entrepreneur and finance interviews.", featured: false },
  { slug: "passive-income", displayName: "Passive income", cluster: "money-investing", description: "Locate passive income ideas and business model breakdowns.", featured: false },
  { slug: "budgeting", displayName: "Budgeting", cluster: "money-investing", description: "Find budgeting systems and cash-flow advice in finance content.", featured: false },
  { slug: "fire", displayName: "FIRE", cluster: "money-investing", description: "Search financial independence and early retirement discussions on YouTube.", featured: false },
  { slug: "index-funds", displayName: "Index funds", cluster: "money-investing", description: "Find index fund investing lessons and long-term portfolio advice.", featured: false },
  { slug: "venture-capital", displayName: "Venture capital", cluster: "money-investing", description: "Search venture capital insights on fundraising, term sheets, and exits.", featured: false },
  { slug: "angel-investing", displayName: "Angel investing", cluster: "money-investing", description: "Locate angel investing advice for deal flow and founder evaluation.", featured: false },
  { slug: "economic-cycles", displayName: "Economic cycles", cluster: "money-investing", description: "Find macroeconomic cycle discussions in finance podcasts.", featured: false },
  { slug: "inflation", displayName: "Inflation", cluster: "money-investing", description: "Search inflation explanations and hedging strategies in market commentary.", featured: false },
  { slug: "retirement-planning", displayName: "Retirement planning", cluster: "money-investing", description: "Find retirement planning guidance in personal finance lectures.", featured: false },
  { slug: "tax-strategy", displayName: "Tax strategy", cluster: "money-investing", description: "Search tax strategy discussions for founders and investors.", featured: false },
  { slug: "financial-freedom", displayName: "Financial freedom", cluster: "money-investing", description: "Locate financial freedom frameworks in money and business content.", featured: false },
  { slug: "side-hustle", displayName: "Side hustle", cluster: "money-investing", description: "Find side hustle ideas and execution advice in creator transcripts.", featured: false },
  { slug: "learning", displayName: "Learning", cluster: "education-lecture", description: "Search learning science, study methods, and skill acquisition in lectures.", featured: true },
  { slug: "education", displayName: "Education", cluster: "education-lecture", description: "Find education policy and pedagogy discussions in academic transcripts.", featured: false },
  { slug: "online-courses", displayName: "Online courses", cluster: "education-lecture", description: "Search online course lectures for modules, exercises, and summaries.", featured: true },
  { slug: "university-lectures", displayName: "University lectures", cluster: "education-lecture", description: "Locate university lecture explanations for exams and revision.", featured: false },
  { slug: "study-tips", displayName: "Study tips", cluster: "education-lecture", description: "Find study tips for retention, focus, and exam performance in videos.", featured: false },
  { slug: "exam-prep", displayName: "Exam prep", cluster: "education-lecture", description: "Search exam prep strategies in coaching and academic content.", featured: false },
  { slug: "skill-building", displayName: "Skill building", cluster: "education-lecture", description: "Find skill-building roadmaps in tutorials and career lectures.", featured: false },
  { slug: "language-learning", displayName: "Language learning", cluster: "education-lecture", description: "Search language learning techniques and immersion advice.", featured: false },
  { slug: "mathematics", displayName: "Mathematics", cluster: "education-lecture", description: "Locate mathematics explanations from algebra through advanced topics.", featured: false },
  { slug: "physics", displayName: "Physics", cluster: "education-lecture", description: "Find physics lecture moments for concepts, proofs, and problem solving.", featured: false },
  { slug: "chemistry", displayName: "Chemistry", cluster: "education-lecture", description: "Search chemistry lessons for reactions, labs, and theory in transcripts.", featured: false },
  { slug: "biology", displayName: "Biology", cluster: "education-lecture", description: "Find biology lectures on cells, genetics, and physiology on YouTube.", featured: false },
  { slug: "history-lessons", displayName: "History lessons", cluster: "education-lecture", description: "Search history lessons for timelines, causes, and primary sources.", featured: false },
  { slug: "philosophy", displayName: "Philosophy", cluster: "education-lecture", description: "Locate philosophy arguments and thought experiments in lecture transcripts.", featured: false },
  { slug: "economics-lecture", displayName: "Economics lecture", cluster: "education-lecture", description: "Find economics lecture explanations for micro, macro, and policy.", featured: false },
  { slug: "critical-thinking", displayName: "Critical thinking", cluster: "education-lecture", description: "Search critical thinking frameworks in academic and debate content.", featured: false },
  { slug: "research-methods", displayName: "Research methods", cluster: "education-lecture", description: "Find research methods guidance for papers, stats, and study design.", featured: false },
  { slug: "teaching", displayName: "Teaching", cluster: "education-lecture", description: "Locate teaching strategies and classroom techniques in educator videos.", featured: false },
  { slug: "tutoring", displayName: "Tutoring", cluster: "education-lecture", description: "Search tutoring walkthroughs for step-by-step problem explanations.", featured: false },
  { slug: "lecture-notes", displayName: "Lecture notes", cluster: "education-lecture", description: "Find lecture note anchors by searching transcript keywords in long classes.", featured: false },
  { slug: "joe-rogan", displayName: "Joe Rogan", cluster: "popular-creator", description: "Search Joe Rogan podcast transcripts for guest quotes and debate moments.", featured: true },
  { slug: "andrew-huberman", displayName: "Andrew Huberman", cluster: "popular-creator", description: "Find Andrew Huberman protocol discussions and neuroscience explanations.", featured: true },
  { slug: "lex-fridman", displayName: "Lex Fridman", cluster: "popular-creator", description: "Search Lex Fridman interview transcripts for AI, philosophy, and science topics.", featured: true },
  { slug: "alex-hormozi", displayName: "Alex Hormozi", cluster: "popular-creator", description: "Locate Alex Hormozi business, offers, and scaling advice in clips.", featured: true },
  { slug: "naval-ravikant", displayName: "Naval Ravikant", cluster: "popular-creator", description: "Find Naval Ravikant wealth, happiness, and startup philosophy moments.", featured: true },
  { slug: "diary-of-a-ceo", displayName: "Diary of a CEO", cluster: "popular-creator", description: "Search Diary of a CEO interviews for founder stories and leadership lessons.", featured: true },
  { slug: "yc-startup-school", displayName: "YC Startup School", cluster: "popular-creator", description: "Find Y Combinator Startup School lectures on product, growth, and fundraising.", featured: true },
  { slug: "tim-ferriss", displayName: "Tim Ferriss", cluster: "popular-creator", description: "Search Tim Ferriss interview transcripts for performance and business tactics.", featured: false },
  { slug: "jordan-peterson", displayName: "Jordan Peterson", cluster: "popular-creator", description: "Locate Jordan Peterson lecture and interview moments on meaning and psychology.", featured: false },
  { slug: "sam-harris", displayName: "Sam Harris", cluster: "popular-creator", description: "Find Sam Harris meditation, ethics, and debate segments in transcripts.", featured: false },
  { slug: "david-goggins", displayName: "David Goggins", cluster: "popular-creator", description: "Search David Goggins motivation and mental toughness quotes in videos.", featured: false },
  { slug: "gary-vee", displayName: "Gary Vee", cluster: "popular-creator", description: "Find Gary Vee marketing and entrepreneurship clips in interview transcripts.", featured: false },
  { slug: "simon-sinek", displayName: "Simon Sinek", cluster: "popular-creator", description: "Search Simon Sinek leadership and purpose talks for timestamped moments.", featured: false },
  { slug: "brene-brown", displayName: "Brené Brown", cluster: "popular-creator", description: "Locate Brené Brown vulnerability and courage discussions in talks.", featured: false },
  { slug: "tony-robbins", displayName: "Tony Robbins", cluster: "popular-creator", description: "Find Tony Robbins coaching and event moments in long-form uploads.", featured: false },
  { slug: "elon-musk-interviews", displayName: "Elon Musk interviews", cluster: "popular-creator", description: "Search Elon Musk interview transcripts for product and company updates.", featured: false },
  { slug: "steve-jobs", displayName: "Steve Jobs", cluster: "popular-creator", description: "Find Steve Jobs keynote and interview quotes about product and design.", featured: false },
  { slug: "bill-gates", displayName: "Bill Gates", cluster: "popular-creator", description: "Search Bill Gates interviews on technology, climate, and philanthropy.", featured: false },
  { slug: "warren-buffett", displayName: "Warren Buffett", cluster: "popular-creator", description: "Locate Warren Buffett investing principles in shareholder meeting transcripts.", featured: false },
  { slug: "ray-dalio", displayName: "Ray Dalio", cluster: "popular-creator", description: "Find Ray Dalio economic principles and decision-making frameworks in talks.", featured: false },
  { slug: "peter-thiel", displayName: "Peter Thiel", cluster: "popular-creator", description: "Search Peter Thiel startup and contrarian strategy moments in interviews.", featured: false },
  { slug: "paul-graham", displayName: "Paul Graham", cluster: "popular-creator", description: "Find Paul Graham essays and talks on startups and writing in video form.", featured: false },
  { slug: "patrick-bet-david", displayName: "Patrick Bet-David", cluster: "popular-creator", description: "Search PBD interview transcripts for business breakdowns and debates.", featured: false },
  { slug: "graham-stephan", displayName: "Graham Stephan", cluster: "popular-creator", description: "Locate Graham Stephan finance and real estate commentary in videos.", featured: false },
  { slug: "ben-shapiro", displayName: "Ben Shapiro", cluster: "popular-creator", description: "Find Ben Shapiro debate and commentary moments in uploaded transcripts.", featured: false },
  { slug: "destiny", displayName: "Destiny", cluster: "popular-creator", description: "Search Destiny political debate transcripts for argument timestamps.", featured: false },
  { slug: "contra-points", displayName: "ContraPoints", cluster: "popular-creator", description: "Find ContraPoints essay video moments through transcript keyword search.", featured: false },
  { slug: "kurzgesagt", displayName: "Kurzgesagt", cluster: "popular-creator", description: "Search Kurzgesagt science explainer transcripts for concepts and facts.", featured: false },
  { slug: "veritasium", displayName: "Veritasium", cluster: "popular-creator", description: "Locate Veritasium physics explanations and experiment breakdowns.", featured: false },
  { slug: "fireship", displayName: "Fireship", cluster: "popular-creator", description: "Find Fireship dev tool summaries and fast-paced coding explainers.", featured: false },
];

export const TOPIC_SEEDS: TopicSeed[] = [...MANUAL_TOPIC_SEEDS, ...GENERATED_TOPIC_SEEDS];
