#!/usr/bin/env tsx
/**
 * Writes TOPIC_INTELLIGENCE_REPORT.md from data/public-moments.json (via topic index).
 *
 *   npm run report:topic-intelligence
 */

import { writeFileSync } from "node:fs";
import { join } from "node:path";

import {
  getTopicIndexBuildStats,
  listTopicHubs,
  resetTopicHubIndexCache,
} from "@/lib/topics/topic-index";
import { buildTopicPath, getSiteUrl } from "@/lib/seo";

function main() {
  resetTopicHubIndexCache();
  const stats = getTopicIndexBuildStats();
  const hubs = listTopicHubs();
  const site = getSiteUrl();

  const top20 = [...hubs]
    .sort((a, b) => b.moments.length - a.moments.length)
    .slice(0, 20)
    .map((h) => `- **${h.displayTitle}** (\`${h.slug}\`) — ${h.moments.length} moments, ${h.quality}`);

  const sampleUrls = hubs
    .filter((h) => h.quality === "hub")
    .slice(0, 12)
    .map((h) => `- ${site}${buildTopicPath(h.slug)}`);

  const weakSample = stats.rejectedWeakLabels.slice(0, 35).map((w) => `- ${w}`);

  const md = `# Topic intelligence report

Generated by \`npm run report:topic-intelligence\` (re-run after updating \`data/public-moments.json\`).

## Summary

| Metric | Value |
|--------|------:|
| Total topic hubs (thin + hub) | **${hubs.length}** |
| Hub-quality (indexable) | **${stats.hubCount}** |
| Thin / exploratory | **${stats.thinCount}** |
| Weak labels rejected (sample cap 400) | **${stats.rejectedWeakLabels.length}** |

## Top 20 topics by moment coverage

${top20.join("\n")}

## Weak topics / labels rejected (sample)

${weakSample.join("\n")}

## Sample hub URLs (hub-quality)

${sampleUrls.join("\n")}

## Internal linking strategy

- **Topic ↔ moment**: every hub surfaces canonical \`/moment/[id]/[slug]\` links for the strongest indexed excerpts.
- **Topic ↔ search**: primary label + related phrases deep-link to \`/search/[query]\` for continued exploration.
- **Topic ↔ video**: aggregate best videos by overlap count to \`/video/[videoId]\`.
- **Topic ↔ creator**: map channel names to \`/creator/[slug]\` where the creator database matches.
- **Topic ↔ topic**: overlap graph connects hubs that share videos (related topic chips).
- **Discovery**: \`/topics\` lists pillar-grouped hubs; sitemap adds **hub-only** intelligence URLs not already covered by curated \`TOPIC_KEYWORDS\`.

## Remaining risks

- **Label noise**: phrase-derived hubs can inherit long spoken fragments; tune grouping in \`lib/topics/topic-index.ts\`.
- **Overlap with curated topics**: seed pages keep canonical metadata; intelligence JSON-LD is emitted only for hub-quality pairings on seed URLs.
- **Stale index**: topic cache is in-memory per server process; redeploy or restart picks up new \`public-moments.json\`.
- **Thin pages**: \`robots: noindex\` reduces SEO noise while preserving crawl paths for internal discovery.

`;

  const out = join(process.cwd(), "TOPIC_INTELLIGENCE_REPORT.md");
  writeFileSync(out, md, "utf-8");
  console.log(`Wrote ${out}`);
}

main();
