#!/usr/bin/env tsx
/**
 * Writes CORPUS_HEALTH_REPORT.md from public moments (no network).
 *
 *   npm run corpus-health-report
 */

import { writeFileSync } from "node:fs";
import { join } from "node:path";

import type { PublicMomentRecord } from "@/lib/moments/public-moment-types";
import { loadPublicMoments } from "@/lib/moments/load-public-moments";
import { evaluatePublicMoment } from "@/lib/quality";
import { evaluateSourceAuthorityForPublicMoment } from "@/lib/research/source-authority";
import { classifyExplanationFromText } from "@/lib/research/classify-explanation-role";
import { averageQualityTierShare } from "@/lib/corpus/topic-coverage";
import { recordCorpusPipelineEvent } from "@/lib/corpus/corpus-analytics";

function isCitationRich(m: PublicMomentRecord): boolean {
  const s = m.semantic;
  if (!s?.citations) return false;
  return Boolean(s.citations.markdown?.length || s.citations.academic?.length);
}

function main() {
  const moments = loadPublicMoments();

  const videoIds = new Set(moments.map((m) => m.videoId));
  const creators = new Set(moments.map((m) => m.channelName).filter(Boolean) as string[]);

  const authorityMix = new Map<string, number>();
  let citeRich = 0;
  let tutorialish = 0;
  let explanationish = 0;
  let weakTier = 0;

  const topicCounts = new Map<string, number>();
  for (const m of moments) {
    const label = evaluateSourceAuthorityForPublicMoment(m).sourceAuthorityLabel;
    authorityMix.set(label, (authorityMix.get(label) ?? 0) + 1);
    if (isCitationRich(m)) citeRich += 1;
    const ev = evaluatePublicMoment(m);
    if (ev.qualityTier === "low") weakTier += 1;

    const cls = classifyExplanationFromText({
      phrase: m.phrase,
      snippet: m.snippet,
      videoTitle: m.videoTitle,
      extractionKinds: m.semantic?.extractionKinds,
    });
    if (cls.tutorialLikelihood >= 1) tutorialish += 1;
    if (cls.beginnerLikelihood >= 1 || cls.technicalLikelihood >= 1) explanationish += 1;

    const t = (m.topic ?? "uncategorized").trim() || "uncategorized";
    topicCounts.set(t, (topicCounts.get(t) ?? 0) + 1);
  }

  const tierShare = averageQualityTierShare(moments);
  const avgTierScore =
    moments.length > 0
      ? ((tierShare.high * 3 + tierShare.medium * 2 + tierShare.low * 1) / 1).toFixed(2)
      : "—";
  const n = moments.length || 1;
  const topTopics = [...topicCounts.entries()].sort((a, b) => b[1] - a[1]).slice(0, 15);

  const tutorialExplanationRatio =
    explanationish > 0 ? (tutorialish / explanationish).toFixed(3) : tutorialish > 0 ? "∞" : "0";

  const md = `# Corpus health snapshot

Generated by \`npm run corpus-health-report\` from \`data/public-moments.json\` at ${new Date().toISOString()}.

## Headline metrics

| Metric | Value |
|--------|------:|
| Indexed moments | ${moments.length} |
| Indexed videos (unique) | ${videoIds.size} |
| Unique creators | ${creators.size} |
| Citation-rich % | ${((citeRich / n) * 100).toFixed(1)}% |
| Weak-signal % (low quality tier) | ${((weakTier / n) * 100).toFixed(1)}% |
| Average quality tier score (1=low … 3=high) | ${avgTierScore} |
| Quality tier mix (high / med / low) | ${(tierShare.high * 100).toFixed(1)}% / ${(tierShare.medium * 100).toFixed(1)}% / ${(tierShare.low * 100).toFixed(1)}% |
| Tutorial / explanation ratio (heuristic) | ${tutorialExplanationRatio} (tutorials=${tutorialish}, explanations=${explanationish}) |

## Source authority mix (labels)

| Label | Count |
|-------|------:|
${[...authorityMix.entries()]
  .sort((a, b) => b[1] - a[1])
  .map(([k, v]) => `| ${k} | ${v} |`)
  .join("\n")}

## Topic distribution (top 15)

| Topic | Moments |
|-------|--------:|
${topTopics.map(([k, v]) => `| ${k} | ${v} |`).join("\n")}
`;

  const out = join(process.cwd(), "CORPUS_HEALTH_REPORT.md");
  writeFileSync(out, md, "utf-8");
  console.log(`Wrote ${out}`);

  if (weakTier / n > 0.35) {
    recordCorpusPipelineEvent("missing_corpus_detected", {
      kind: "corpus_health_weak_signal_share",
      weakShare: weakTier / n,
    });
  }
}

main();
