#!/usr/bin/env tsx
/**
 * Writes data/public-moments.json — quality-filtered canonical /moment/[id]/[slug] rows.
 *
 *   npm run materialize:public-moments
 *   PUBLIC_MOMENTS_CAP=140 PUBLIC_MOMENTS_PER_VIDEO=12 npm run materialize:public-moments
 */

import { writeFileSync } from "node:fs";
import { join } from "node:path";

import { getIndexedVideoById } from "@/lib/indexed-videos";
import { evaluateMomentMaterialization } from "@/lib/moments/public-moment-quality";
import type { PublicMomentRecord } from "@/lib/moments/public-moment-types";
import { computePublicMomentStableId } from "@/lib/moments/stable-id";
import { hybridFindMatches } from "@/lib/search/per-video-hybrid-search";
import { getSiteUrl, slugifyQuery } from "@/lib/seo";
import { suggestKeywords } from "@/lib/transcript-search";
import { getCachedTranscript, listCachedTranscripts } from "@/lib/transcript-cache";
import type { TranscriptLine } from "@/lib/transcript-types";

const CAP = Math.min(150, Math.max(50, Number(process.env.PUBLIC_MOMENTS_CAP ?? 120)));
const KEYWORD_POOL = Number(process.env.PUBLIC_MOMENTS_KEYWORD_POOL ?? 64);
const MAX_PER_VIDEO = Number(process.env.PUBLIC_MOMENTS_PER_VIDEO ?? 10);

type Candidate = PublicMomentRecord & { qualityScore: number };

type RejectLog = { videoId: string; phrase: string; reason: string; totalScore?: number };
type AcceptLog = { videoId: string; phrase: string; totalScore: number };

function toTranscriptLines(
  segments: Array<{ text: string; start: number; duration?: number }>
): TranscriptLine[] {
  return segments.map((segment) => ({
    text: segment.text,
    start: segment.start,
    duration: segment.duration ?? 0,
  }));
}

function disambiguateSlug(base: string, used: Set<string>) {
  let slug = base;
  let n = 0;
  while (used.has(slug)) {
    n += 1;
    slug = `${base}-${n}`;
  }
  used.add(slug);
  return slug;
}

function buildMarkdownReport(params: {
  accepted: AcceptLog[];
  rejectedSample: RejectLog[];
  moments: PublicMomentRecord[];
  minStrict: number;
  minSoft: number;
  cap: number;
}) {
  const site = getSiteUrl();
  const sampleUrls = params.moments.slice(0, 5).map((m) => `${site}/moment/${m.id}/${m.canonicalSlug}`);

  const acceptRows = params.accepted
    .slice(0, 18)
    .map((a) => `| ${a.phrase} | ${a.videoId} | ${a.totalScore} |`)
    .join("\n");

  const rejectRows = params.rejectedSample
    .slice(0, 22)
    .map((r) => `| ${r.phrase} | ${r.videoId} | ${r.reason} | ${r.totalScore ?? "—"} |`)
    .join("\n");

  return `# Public moment quality & materialization

Generated by \`npm run materialize:public-moments\` (do not hand-edit counts; re-run the script).

## Quality rules (code)

- Reject ultra-generic **single-word** stems and a shared **GENERIC_MOMENT_TOKENS** blocklist (\`lib/moments/public-moment-quality.ts\`).
- Boost **"what is / what are"**, **"how to"**, **questions**, **digits**, **longer multi-word phrases**, **mixed-case hints**, and a small **tech lexicon** overlap.
- Require **snippet length** ≥ 88 chars and that the **phrase is reflected** in the merged snippet.
- **Strict** gate default: combined score ≥ **${params.minStrict}**; if fewer than 50 moments pass, a **soft** pass (≥ **${params.minSoft}**) fills toward the cap without re-scraping transcripts.

## Acceptance summary

| Metric | Value |
|--------|------:|
| Final moment count | **${params.moments.length}** |
| Target cap | **${params.cap}** |
| Accepted (logged) | **${params.accepted.length}** |

### Accepted examples (sample)

| Phrase | videoId | score |
|--------|---------|------:|
${acceptRows}

### Rejected examples (sample)

| Phrase | videoId | reason | score |
|--------|---------|--------|------|
${rejectRows}

## Sample canonical URLs (production host from \`getSiteUrl()\` at generation time)

${sampleUrls.map((u) => `- ${u}`).join("\n")}

## OG / sharing

Moment OG routes use \`lib/og-moment-share-image.tsx\` (simple layout, system font, no italic) with try/catch fallback PNG.

## Remaining risks

- **Transcript drift**: hybrid match position can move slightly vs older materialized \`startSeconds\` after re-ingest (stable id still matches tuple).
- **Score thresholds** are heuristics; tune \`evaluateMomentMaterialization\` and env caps if the pool is too small or too noisy.

`;
}

async function main() {
  const summaries = await listCachedTranscripts();
  const usedSlugs = new Set<string>();
  const rejected: RejectLog[] = [];
  const pool: Candidate[] = [];

  const minStrict = 20;
  const minSoft = 12;

  for (const summary of summaries) {
    const cached = await getCachedTranscript(summary.videoId);
    if (!cached || cached.segments.length === 0) continue;

    const lines = toTranscriptLines(cached.segments);
    const keywords = suggestKeywords(lines, "", KEYWORD_POOL);
    const indexed = await getIndexedVideoById(summary.videoId);
    const category = indexed?.category ?? cached.category ?? undefined;
    const topic = indexed?.topic ?? undefined;

    for (const phrase of keywords) {
      const trimmed = phrase.trim();
      if (!trimmed) continue;

      const results = hybridFindMatches(summary.videoId, lines, trimmed);
      const top = results[0];
      if (!top) {
        rejected.push({ videoId: summary.videoId, phrase: trimmed, reason: "no_hybrid_match" });
        continue;
      }

      const strict = evaluateMomentMaterialization(trimmed, top.snippet, minStrict);
      const soft = strict.pass ? strict : evaluateMomentMaterialization(trimmed, top.snippet, minSoft);
      const gate = strict.pass ? strict : soft;

      if (!gate.pass || !gate.snippet.ok) {
        rejected.push({
          videoId: summary.videoId,
          phrase: trimmed,
          reason: gate.snippet.reason ?? `below_threshold_${gate.totalScore}`,
          totalScore: gate.totalScore,
        });
        continue;
      }

      if (!strict.pass && gate.pass) {
        if (gate.phrase.score < -25) {
          rejected.push({
            videoId: summary.videoId,
            phrase: trimmed,
            reason: "soft_gate_blocked_weak_phrase",
            totalScore: gate.totalScore,
          });
          continue;
        }
      }

      const id = computePublicMomentStableId(summary.videoId, top.start, trimmed);
      const baseSlug = slugifyQuery(trimmed);
      const canonicalSlug = disambiguateSlug(baseSlug, usedSlugs);

      pool.push({
        id,
        videoId: summary.videoId,
        phrase: trimmed,
        canonicalSlug,
        startSeconds: top.start,
        timestamp: top.timestamp,
        snippet: top.snippet,
        youtubeUrl: top.openUrl,
        videoTitle: indexed?.title,
        channelName: indexed?.channelName ?? undefined,
        category,
        topic,
        qualityScore: gate.totalScore,
        materializedAt: new Date().toISOString(),
      });
    }
  }

  pool.sort((a, b) => (b.qualityScore ?? 0) - (a.qualityScore ?? 0));

  const byId = new Map<string, Candidate>();
  for (const c of pool) {
    const prev = byId.get(c.id);
    if (!prev || (c.qualityScore ?? 0) > (prev.qualityScore ?? 0)) {
      byId.set(c.id, c);
    }
  }

  const unique = [...byId.values()].sort((a, b) => (b.qualityScore ?? 0) - (a.qualityScore ?? 0));

  const perVideo = new Map<string, number>();
  const moments: PublicMomentRecord[] = [];

  for (const c of unique) {
    if (moments.length >= CAP) break;
    const n = perVideo.get(c.videoId) ?? 0;
    if (n >= MAX_PER_VIDEO) continue;
    perVideo.set(c.videoId, n + 1);
    const { qualityScore, ...rest } = c;
    moments.push({ ...rest, qualityScore });
  }

  const accepted: AcceptLog[] = moments.map((m) => ({
    videoId: m.videoId,
    phrase: m.phrase,
    totalScore: m.qualityScore ?? 0,
  }));

  const outPath = join(process.cwd(), "data/public-moments.json");
  writeFileSync(outPath, `${JSON.stringify({ moments }, null, 2)}\n`, "utf-8");

  const validationPath = join(process.cwd(), "data/public-moments-validation.json");
  writeFileSync(
    validationPath,
    `${JSON.stringify(
      {
        generatedAt: new Date().toISOString(),
        cap: CAP,
        keywordPool: KEYWORD_POOL,
        maxPerVideo: MAX_PER_VIDEO,
        minStrict,
        minSoft,
        acceptedCount: accepted.length,
        finalCount: moments.length,
        rejectedSample: rejected.slice(0, 400),
        acceptedSample: accepted.slice(0, 200),
      },
      null,
      2
    )}\n`,
    "utf-8"
  );

  const reportPath = join(process.cwd(), "PUBLIC_MOMENT_QUALITY_REPORT.md");
  writeFileSync(
    reportPath,
    buildMarkdownReport({
      accepted,
      rejectedSample: rejected,
      moments,
      minStrict,
      minSoft,
      cap: CAP,
    }),
    "utf-8"
  );

  console.log(`Wrote ${moments.length} public moments to ${outPath}`);
  console.log(`Wrote validation log to ${validationPath}`);
  console.log(`Wrote ${reportPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
