#!/usr/bin/env tsx
/**
 * Writes MISSING_CORPUS_REPORT.md and data/missing-corpus.json
 *
 * Optional input: copy analytics export to data/analytics/source-index-requests.json
 * or symlink data/analytics/source-index-requests.sample.json for a dry run.
 *
 *   npm run missing-corpus-report
 */

import { existsSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { loadPublicMoments } from "@/lib/moments/load-public-moments";
import { buildTopicCoverageReport } from "@/lib/corpus/topic-coverage";
import { buildMissingCorpusReport } from "@/lib/corpus/missing-corpus";
import { recordCorpusPipelineEvent } from "@/lib/corpus/corpus-analytics";

function main() {
  const requestsReal = join(process.cwd(), "data", "analytics", "source-index-requests.json");
  const requestsSample = join(process.cwd(), "data", "analytics", "source-index-requests.sample.json");
  const requestsPath = existsSync(requestsReal) ? requestsReal : requestsSample;

  const moments = loadPublicMoments();
  const coverage = buildTopicCoverageReport(moments);
  const { findings, requests } = buildMissingCorpusReport({ moments, coverage, requestsPath });

  const jsonPath = join(process.cwd(), "data", "missing-corpus.json");
  writeFileSync(
    jsonPath,
    JSON.stringify({ generatedAt: new Date().toISOString(), findings, requestCount: requests.length }, null, 2),
    "utf-8"
  );

  const md = `# Missing corpus report

Generated by \`npm run missing-corpus-report\`.

## Inputs

- Public moments: \`data/public-moments.json\`
- Optional requests: \`data/analytics/source-index-requests.json\` (export \`source_index_request\` payloads from analytics)

## Findings (${findings.length})

${findings
  .slice(0, 80)
  .map((f) => `- **${f.kind}** (w=${f.weight}): ${f.detail}`)
  .join("\n")}

`;

  const out = join(process.cwd(), "MISSING_CORPUS_REPORT.md");
  writeFileSync(out, md, "utf-8");
  console.log(`Wrote ${jsonPath}`);
  console.log(`Wrote ${out}`);

  if (findings.length > 0) {
    recordCorpusPipelineEvent("missing_corpus_detected", {
      findingCount: findings.length,
      kinds: [...new Set(findings.map((f) => f.kind))].join(","),
    });
  }
}

main();
