#!/usr/bin/env tsx
/**
 * Writes TOPIC_COVERAGE_REPORT.md and data/topic-coverage.json from public moments.
 *
 *   npm run topic-coverage-report
 */

import { writeFileSync } from "node:fs";
import { join } from "node:path";

import { loadPublicMoments } from "@/lib/moments/load-public-moments";
import { buildTopicCoverageReport } from "@/lib/corpus/topic-coverage";

function main() {
  const moments = loadPublicMoments();
  const rows = buildTopicCoverageReport(moments);

  const jsonPath = join(process.cwd(), "data", "topic-coverage.json");
  writeFileSync(jsonPath, JSON.stringify({ generatedAt: new Date().toISOString(), rows }, null, 2), "utf-8");

  const tableHeader = `| Topic | Moments | Videos | Creators | Beginner % | Technical % | Counter % | Cite-rich % |
|-------|--------:|-------:|---------:|-----------:|------------:|----------:|------------:|
`;

  const tableRows = rows
    .slice(0, 25)
    .map(
      (r) =>
        `| ${r.topic} | ${r.numberOfMoments} | ${r.numberOfVideos} | ${r.uniqueCreators} | ${(r.beginnerCoverage * 100).toFixed(0)}% | ${(r.technicalCoverage * 100).toFixed(0)}% | ${(r.counterpointCoverage * 100).toFixed(0)}% | ${(r.citationRichCoverage * 100).toFixed(0)}% |`
    )
    .join("\n");

  const md = `# Topic coverage report

Generated by \`npm run topic-coverage-report\` from \`data/public-moments.json\`.

## Summary

| Topics tracked | ${rows.length} |
| Total moments | ${moments.length} |

## Under-covered / weak depth (heuristic flags)

${rows
  .filter((r) => r.weakComparisonDepth || r.missingBeginner || r.missingCounterpoint)
  .slice(0, 40)
  .map(
    (r) =>
      `- **${r.topic}** — moments ${r.numberOfMoments}, videos ${r.numberOfVideos}, creators ${r.uniqueCreators}, auth diversity ${r.authorityDiversity} — weakDepth=${r.weakComparisonDepth}, missingBeginner=${r.missingBeginner}, missingCounterpoint=${r.missingCounterpoint}`
  )
  .join("\n")}

## Top topics by moment count

${tableHeader}${tableRows}
`;

  const out = join(process.cwd(), "TOPIC_COVERAGE_REPORT.md");
  writeFileSync(out, md, "utf-8");
  console.log(`Wrote ${jsonPath}`);
  console.log(`Wrote ${out}`);
}

main();
